### ISSUE TITLE
Name collision in KustoResultIter

### ISSUE THREAD

**Issue by hahmed1** [Azure/azure-kusto-python#11]
The name collision between the instance attribute and method "next" in the KustoResultIter class is causing me to get "TypeError: 'int' object is not callable" whenever I try advancing my iterator instance with iter.next().  

See also: https://stackoverflow.com/questions/12949064/python-what-happens-when-class-attribute-instance-attribute-and-method-all-ha

**Comment by toshetah** [comment]
This issue was fixed at https://github.com/Azure/azure-kusto-python/commit/413d6be44f83b0e3290c3df91746f4aab913ca94

Thanks!
