### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jruales** [Azure/azure-kusto-python#121]
When running the following, I get a cryptic `TypeError: string indices must be integers` error. Either this is a bug on the Kusto side, or Kusto should provide a better error message.

Note: The below code works if I change `execute_query` into `execute` or `execute_mgmt`

```
from azure.kusto.data.request import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties
from azure.kusto.data.exceptions import KustoServiceError
from azure.kusto.data.helpers import dataframe_from_result_table

cluster = "https://help.kusto.windows.net"

# In case you want to authenticate with AAD device code.
# Please note that if you choose this option, you'll need to autenticate for every new instance that is initialized.
# It is highly recommended to create one instance and use it for all of your queries.
kcsb = KustoConnectionStringBuilder.with_aad_device_authentication(cluster)

# The authentication method will be taken from the chosen KustoConnectionStringBuilder.
client = KustoClient(kcsb)

response = client.execute_query('Samples', '.show schema')
```

**Comment by danield137** [comment]
Thanks for reporting this @jruales, 
When calling `execute`, we check the query given, and if it starts with a dot, it means it is a management command and not a query ([read more about it here](https://docs.microsoft.com/en-us/azure/kusto/management/#differentiating-control-commands-from-queries)).
That should explain why we have the more explicit function: `execute_query` and `execute_mgmt`.

It is a bug that we do not make sure the proper method was called.
We should probably add a validity check and maybe even consider notating them as private (`_prefix`).

@toshetah @vladikbr

**Comment by danield137** [comment]
@jruales I cannot seem to be able to reproduce the error. 
I'm getting a relevant exception stating control commands are not allowed on query endpoint.

Could you specify the client version you are using?

**Comment by jruales** [comment]
You're right, I don't see the cryptic error anymore. Thanks to whoever fixed it.
