### ISSUE TITLE
How to store query result to csv?

### ISSUE THREAD

**Issue by dpengwang** [Azure/azure-kusto-python#130]

**Comment by ArielYehezkely** [comment]
Hi @dpengwang , 

As shown in the [sample](https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/tests/sample.py) the result table can be converted to DataFrame, which supports export to csv.
For example:
`from azure.kusto.data.helpers import dataframe_from_result_table`

`response = client.execute(Database, Query)`
`dataframe = dataframe_from_result_table(response.primary_results[0])`
`dataframe.to_csv("results.csv", index=False, encoding="utf-8", header=True)`

**Comment by danield137** [comment]
@dpengwang feel free to ask such questions on stackoverflow.com using [azure data explorer tag](https://stackoverflow.com/questions/tagged/azure-data-explorer)
