### ISSUE TITLE
Support for Azure managed identity for authorization

### ISSUE THREAD

**Issue by j03wang** [Azure/azure-kusto-python#135]
It would be great if the SDK supported retrieving auth tokens from the Azure managed identity endpoint when running on Azure resources.

**Comment by danield137** [comment]
Hi @j03wang not sure what you mean by that, could you please reference docs or a code sample?

**Comment by toshetah** [comment]
Hi @j03wang,

We can add support of the client to retrieve token, and use it for authenticating.
Is that what you meant?

Thanks,
Tomer

**Comment by j03wang** [comment]
@toshetah Yes - like what's describe [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token), so that I wouldn't need to specify any sort of client credentials at all.

**Comment by toshetah** [comment]
@j03wang , thank you for your suggestion.
We've created a [pull request](https://github.com/Azure/azure-kusto-python/pull/137) to support this scenario.

**Comment by j03wang** [comment]
Thanks - any ETA on when this might be released?

**Comment by danield137** [comment]
https://github.com/Azure/azure-kusto-python/releases/tag/v0.0.30

**Comment by ChrisCoe** [comment]
It would be nice to have some documentation on this. Can someone elaborate?
