### ISSUE TITLE
Consider moving KustoClient

### ISSUE THREAD

**Issue by danield137** [Azure/azure-kusto-python#138]
Currently, importing `KustoIngestClient` is from top level module, while `KustoClient` isn't.

```python
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder
from azure.kusto.ingest import KustoIngestClient
```

Should consider a better design decision that will be consistent between the packages

**Comment by TzviaGT** [comment]
Daniel already fixed it

**Comment by vladikbr** [comment]
Looks like this is already done
