### ISSUE TITLE
Add support for azure cli auth

### ISSUE THREAD

**Issue by danield137** [Azure/azure-kusto-python#139]
Grab token from underlying azure cli

Docs: 
* https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-get-access-token

* https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest

**Comment by alexkyllo** [comment]
Just to confirm--it would work like this, right?
```python
from azure.common.client_factory import get_client_from_cli_profile
from azure.kusto.data.request import KustoClient
client = get_client_from_cli_profile(KustoClient)
```
Adapted from this example: https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli

BTW, do you know if there is any workaround today to get a KustoClient to authenticate from CLI profile? I'm working on a script that creates some functions in Kusto and sets up Azure Data Factory pipelines that call the functions on a schedule, and trying to avoid using two different auth methods for Kusto and ADF...

**Comment by danield137** [comment]
To be able to do so, we would have to be a part of the azure-cli project, which is not currently a priority.

I was thinking more along the lines of:
```python
def get_azure_cli_auth_token():
    import subprocess
    p = subprocess.run("az account get-access-token", shell=True, stdout=subprocess.PIPE)
    result = p.stdout.decode()

    return result


token = json.loads(get_azure_cli_auth_token())
user_token="{tokenType} {accessToken}".format(**token)
kcsb = KustoConnectionStringBuilder.with_aad_user_token_authentication(user_token=user_token)
```

**Comment by danield137** [comment]
https://github.com/Azure/azure-kusto-python/tree/v0.0.43
