### ISSUE TITLE
How authorize a user to access two different cluster in the same time ？

### ISSUE THREAD

**Issue by dpengwang** [Azure/azure-kusto-python#140]
Nowdays, I need to get data from one cluster and I need to use other cluster's function.But I can only use AAD to access one cluster at a time, How can I do?

**Comment by danield137** [comment]
I'm not sure exactly what is it you need.

If you mean you need to query another cluster from within a query, that is possible, and the credentials provided to access kusto will propagate to the other cluster. This is called [cross cluster queries](https://docs.microsoft.com/en-us/azure/kusto/query/joincrosscluster).

If you mean you have multiple identities, then just create multiple clients.

Please ask these kind of question at https://stackoverflow.com/questions/tagged/azure-data-explorer
