### ISSUE TITLE
JSONDecodeError on error response

### ISSUE THREAD

**Issue by olehb007** [Azure/azure-kusto-python#146]
If query execution doesn't succeed kusto plugin fails to parse error as it's not in a json format, e.g.

`JSONDecodeError                           Traceback (most recent call last)
<ipython-input-34-27d4e01b2255> in <module>
----> 1 drop_response = client.execute(db_aliases["Trouter Client PROD"], drop_command)
      2 drop_response

~/anaconda3_501/lib/python3.6/site-packages/azure/kusto/data/request.py in execute(self, database, query, properties)
    393         """
    394         if query.startswith("."):
--> 395             return self.execute_mgmt(database, query, properties)
    396         return self.execute_query(database, query, properties)
    397 

~/anaconda3_501/lib/python3.6/site-packages/azure/kusto/data/request.py in execute_mgmt(self, database, query, properties)
    416         :rtype: azure.kusto.data._response.KustoResponseDataSet
    417         """
--> 418         return self._execute(self._mgmt_endpoint, database, query, None, KustoClient._mgmt_default_timeout, properties)
    419 
    420     def execute_streaming_ingest(self, database, table, stream, stream_format, properties=None, mapping_name=None):

~/anaconda3_501/lib/python3.6/site-packages/azure/kusto/data/request.py in _execute(self, endpoint, database, query, payload, timeout, properties)
    463             return KustoResponseDataSetV1(response.json())
    464 
--> 465         raise KustoServiceError([response.json()], response)
    466 
    467     def _get_timeout(self, properties, default):

~/anaconda3_501/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~/anaconda3_501/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder
`

**Comment by zhipenghan** [comment]
I got similar error. After I changed the database_name to the database_id, it works fine.

**Comment by alwils** [comment]
Same error here... after debugging and stepping through the code I was finding this error was due to a 400 Response back "'database' not found". After I changed the database Name to the database ID it works perfectly.

**Comment by flamtapgt** [comment]
Same Error 

I found the database id using 
`.show database identity`

I passed this database_id to client.execute() but it did not resolve my problem.
```
db_id = '***redacted***'
query = 'BatchInfo'  # BatchInfo is the table name
response = client.execute(db_id, query)
```
 
Error message is the same as shown above except we are using 
/usr/anaconda/lib/python3.7/

**Comment by flamtapgt** [comment]
I was seeing this error, but then realized that my cluster was set to `https://ingest-something.kusto.net ` instead of `https://something.kusto.net`. 

For me, the database name worked in the query, not the database ID.

**Comment by danield137** [comment]
Thanks @flamtapgt for sharing, we will implement a mechanizem to warn in such cases.
