### ISSUE TITLE
Fail to connect contry cloud adx endpoint

### ISSUE THREAD

**Issue by nonokangwei** [Azure/azure-kusto-python#148]
for the azure-kusto-data sdk, there has no where to setup the login endpoin  for  AAD authentication. in Azure China, there has launch ADX, but can not connect using python SDK yet.

**Comment by danield137** [comment]
Hi @nonokangwei, Thanks for reporting! you are correct, this is a current limitation, and it's by design. we are discussing internally on a simple way to implement it here as well.
Will update the issue.

**Comment by danield137** [comment]
Hi @nonokangwei , please note that since version 0.0.37 we allow to pass in a different authentication url.

Check this out release https://github.com/Azure/azure-kusto-python/releases/tag/v0.0.37
