### ISSUE TITLE
DataFormat is not found

### ISSUE THREAD

**Issue by iamnancy07** [Azure/azure-kusto-python#15]
I tried the kusto ingest code on Readme and it says DataFormat is not found....

**Comment by ntomczek** [comment]
Ran into a similar issue. I was able to fix it using by changing my IngestionProperties to the follwing: 
`IngestionProperties(database=db, table=tablename, dataFormat='csv')`

**Comment by danield137** [comment]
Closing. Please reopen if not resolved.
