### ISSUE TITLE
Why 'culster' is the necessary parameter , it limit the query cross clusters

### ISSUE THREAD

**Issue by dpengwang** [Azure/azure-kusto-python#151]

**Comment by danield137** [comment]
I'm sure I follow, what is you suggestion?

You can do cross cluster queries by explicitly stating the cluster as [explained here](https://docs.microsoft.com/en-us/azure/kusto/query/joincrosscluster)

The only limitation here, is the a client instance is per cluster, the reason for that is that it save you the trouble of explicitly providing the uri each query.

If I failed to understand, please do elaborate

**Comment by danield137** [comment]
Closing due to lack of response.

A `KustoClient` instance as a cluster specific (authorization is requested for that specific cluster). 

If we will see other requests for having a non cluster specific cluster, we will reopen this issue.
