### ISSUE TITLE
typo in KustoResultColumn __init__

### ISSUE THREAD

**Issue by roeap** [Azure/azure-kusto-python#155]
#### Problem description
there is a typo in the __init__ function of `KustoResultColumn`. parameter `ordianl` should be `ordinal`
https://github.com/Azure/azure-kusto-python/blob/b09e80f26393cf6c45f0f353e853753c00f129c4/azure-kusto-data/azure/kusto/data/_models.py#L113

**Comment by danield137** [comment]
thanks for reporting.
fixed in https://github.com/Azure/azure-kusto-python/pull/156
