### ISSUE TITLE
Parquet support in python

### ISSUE THREAD

**Issue by james-tn** [Azure/azure-kusto-python#158]
#### Code Sample, a copy-pastable example if possible

```python
INGESTION_CLIENT = KustoIngestClient(KCSB_INGEST)
FILE_SIZE = 64158321    # in bytes

# All ingestion properties are documented here: https://docs.microsoft.com/azure/kusto/management/data-ingest#ingestion-properties
INGESTION_PROPERTIES = IngestionProperties(database=KUSTO_DATABASE, table=DESTINATION_TABLE, dataFormat=DataFormat.parquet,
                                           mappingReference=DESTINATION_TABLE_COLUMN_MAPPING, additionalProperties={"creationTime":"2019-08-21"})
# FILE_SIZE is the raw size of the data in bytes
for BLOB_PATH in blob_list[0]:
    BLOB_DESCRIPTOR = BlobDescriptor(BLOB_PATH, FILE_SIZE)
    INGESTION_CLIENT.ingest_from_blob(
        BLOB_DESCRIPTOR, ingestion_properties=INGESTION_PROPERTIES)

print('Done queuing up ingestion with Azure Data Explorer')
```
#### Problem description

I set everything parquet but after running the ingestion, the library still thought I import csv. This is error from ADX
"Details": Mapping reference 'PARQUET_Mapping' of type 'csv' in database 'db01' could not be found.,

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]

</details>

**Comment by james-tn** [comment]
I think it's because of this outdated code, it return csv if format is set as "parquet". Need to fix this at least.
    def get_mapping_format(self):
        """Dictating the corresponding mapping to the format."""
        if self.format in [DataFormat.json, DataFormat.singlejson, DataFormat.multijson]:
            return DataFormat.json.name
        elif self.format == DataFormat.avro:
            return DataFormat.avro.name
        else:
            return DataFormat.csv.name

**Comment by danield137** [comment]
Hi @james-tn , to the best of my knowledge, as of this moment, Parquet is not supported. Link me if you saw something stating otherwise.

Regarding the strange piece of code you see, that is due to internal decision made which are somewhat confusing. 
Essentially there are only 3 supported types:
1. Json (with variants , like json lines)
2. CSV (with variants, of *-sv nature, like psv, tsv and so forth)
3. Avro 

So the fallback type is CSV, because it is less exhaustive to write.

**Comment by james-tn** [comment]
Pls reopen this ticket. Parquet is supported at the core engine

**Comment by boazsha** [comment]
Added with version 0.0.35 (pull request #168)
