### ISSUE TITLE
SDK for .purge operation

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-kusto-python#165]
@thisisnish commented on [Fri Aug 23 2019](https://github.com/Azure/azure-sdk-for-python/issues/6928)

Of three python sdks listed here https://docs.microsoft.com/en-us/azure/kusto/api/python/kusto-python-client-library, none of them currently support `.purge` operation. Is this correct or am I missing something? How can one send `.purge` command using python sdk? Will this be incorporated in futire release of `azure-kusto-mgmt` library? 

---

@kaerm commented on [Fri Aug 23 2019](https://github.com/Azure/azure-sdk-for-python/issues/6928#issuecomment-524479337)

Hi @thisisnish thanks for letting us know, I'm tagging relevant teams to help with this

---

@thisisnish commented on [Tue Aug 27 2019](https://github.com/Azure/azure-sdk-for-python/issues/6928#issuecomment-525437299)

@kaerm any update or information on this?

---

@kaerm commented on [Tue Aug 27 2019](https://github.com/Azure/azure-sdk-for-python/issues/6928#issuecomment-525462505)

@thisisnish working on finding the right team

**Comment by danield137** [comment]
Hi @kaerm and @thisisnish , not really sure I understand the question.
It should be perfectly valid to run a `.purge` command by using the `azure-kusto-data` package.

If you are having issues, do provide an example snippet...

**Comment by thisisnish** [comment]
hi @danield137 sorry for delayed response. i tried executing `.purge` query using `azure-kusto-data` package and it gave me same error as in console (via dataexplorer). 
`In [23]: cluster = "https://devmetrics.eastus2.kusto.windows.net"

In [24]: kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(cluster, client_id, client_secret, authority_id)

In [25]: client = KustoClient(kcsb)

In [26]: query = "User | where UserId == 'nish@AdobeOrg'"

In [27]: response = client.execute(db, query)

In [28]: response.primary_results[0][0]
Out[28]: KustoResultRow(['TimeStamp', 'DisplayName', 'GroupName', 'IPAddress', 'UserId', 'GroupId', 'SessionId', 'Data', 'MetricsState', 'DeviceId', 'InstanceId', 'PayloadSequence', 'UserAgent', 'UserHash', 'WindowId', 'Event', 'TenantId', 'Environment', 'MetricsVersion'], [datetime.datetime(2019, 8, 21, 21, 45, 1, 482000, tzinfo=tzutc()), '', '', '::1', 'nish@AdobeOrg', '', '', None, None, '', '', None, 'curl/7.54.0', '2b592574158d2e6936cae728db864530bedb3a5cc7f59f8410953c12565fc7e7', '', '', '', '', ''])

In [29]: query = ".purge table User records in database Metrics with (noregrets='true') <| where UserId ==  'nish@AdobeOrg'"

In [30]: response = client.execute(db, query)
---------------------------------------------------------------------------
KustoServiceError                         Traceback (most recent call last)
<ipython-input-30-4797736f3eac> in <module>
----> 1 response = client.execute(db, query)

/usr/local/lib/python3.7/site-packages/azure/kusto/data/request.py in execute(self, database, query, properties)
    393         """
    394         if query.startswith("."):
--> 395             return self.execute_mgmt(database, query, properties)
    396         return self.execute_query(database, query, properties)
    397

/usr/local/lib/python3.7/site-packages/azure/kusto/data/request.py in execute_mgmt(self, database, query, properties)
    416         :rtype: azure.kusto.data._response.KustoResponseDataSet
    417         """
--> 418         return self._execute(self._mgmt_endpoint, database, query, None, KustoClient._mgmt_default_timeout, properties)
    419
    420     def execute_streaming_ingest(self, database, table, stream, stream_format, properties=None, mapping_name=None):

/usr/local/lib/python3.7/site-packages/azure/kusto/data/request.py in _execute(self, endpoint, database, query, payload, timeout, properties)
    464             return KustoResponseDataSetV1(response.json())
    465
--> 466         raise KustoServiceError([response.json()], response)
    467
    468     def _get_timeout(self, properties, default):

KustoServiceError: (KustoServiceError(...), [{'error': {'code': 'Bad request', 'message': 'Request is invalid and cannot be executed.', '@type': 'Kusto.Data.Exceptions.SyntaxException', '@message': "Syntax error: Query could not be parsed: . Query: '.purge table User records in database Metrics with (noregrets='true') <| where UserId ==  'nish@AdobeOrg''", '@context': {'timestamp': '2019-09-04T23:02:46.0990939Z', 'serviceAlias': 'DEVMETRICS', 'machineName': 'KEngine000000', 'processName': 'Kusto.WinSvc.Svc', 'processId': 8368, 'threadId': 8536, 'appDomainName': 'Kusto.WinSvc.Svc.exe', 'clientRequestd': 'KPC.execute;38cbdeee-1d49-4e09-b0ef-64a01528af47', 'activityId': '48403d3a-7272-4432-ba42-d10c5258ee0f', 'subActivityId': 'd3ce04ba-4af5-4936-8a31-091c9cbf6d53', 'activityType': 'DN.FE.ExecuteControlCommand', 'parentActivityId': '4f3e8e65-ab29-41c9-a0c2-b58eb24cf0fb', 'activityStack': '(Activity stack: CRID=KPC.execute;38cbdeee-1d49-4e09-b0ef-64a01528af47 ARID=48403d3a-7272-4432-ba42-d10c5258ee0f > DN.Admin.Client.ExecuteControlCommand/4f6c57a4-6d3d-4482-9c4f-5cb57e3496f6 > P.WCF.Service.ExecuteControlCommandInternal..IAdminClientServiceCommunicationContract/4f3e8e65-ab29-41c9-a0c2-b58eb24cf0fb > DN.FE.ExecuteControlCommand/d3ce04ba-4af5-4936-8a31-091c9cbf6d53)'}, '@permanent': True}}])

In [31]: query = ".purge table User records in database Metrics with (noregrets='true') where UserId ==  'nish@AdobeOrg'"

In [32]: response = client.execute(db, query)
---------------------------------------------------------------------------
KustoServiceError                         Traceback (most recent call last)
<ipython-input-32-4797736f3eac> in <module>
----> 1 response = client.execute(db, query)

/usr/local/lib/python3.7/site-packages/azure/kusto/data/request.py in execute(self, database, query, properties)
    393         """
    394         if query.startswith("."):
--> 395             return self.execute_mgmt(database, query, properties)
    396         return self.execute_query(database, query, properties)
    397

/usr/local/lib/python3.7/site-packages/azure/kusto/data/request.py in execute_mgmt(self, database, query, properties)
    416         :rtype: azure.kusto.data._response.KustoResponseDataSet
    417         """
--> 418         return self._execute(self._mgmt_endpoint, database, query, None, KustoClient._mgmt_default_timeout, properties)
    419
    420     def execute_streaming_ingest(self, database, table, stream, stream_format, properties=None, mapping_name=None):

/usr/local/lib/python3.7/site-packages/azure/kusto/data/request.py in _execute(self, endpoint, database, query, payload, timeout, properties)
    464             return KustoResponseDataSetV1(response.json())
    465
--> 466         raise KustoServiceError([response.json()], response)
    467
    468     def _get_timeout(self, properties, default):

KustoServiceError: (KustoServiceError(...), [{'error': {'code': 'Bad request', 'message': 'Request is invalid and cannot be executed.', '@type': 'Kusto.Data.Exceptions.SyntaxException', '@message': "Syntax error: Query could not be parsed: . Query: '.purge table User records in database Metrics with (noregrets='true') where UserId ==  'nish@AdobeOrg''", '@context': {'timestamp': '2019-09-04T23:03:20.6859064Z', 'serviceAlias': 'DEVMETRICS', 'machineName': 'KEngine000000', 'processName': 'Kusto.WinSvc.Svc', 'processId': 8368, 'threadId': 5864, 'appDomainName': 'Kusto.WinSvc.Svc.exe', 'clientRequestd': 'KPC.execute;a692efbc-6da9-476c-84a7-10097afbe84a', 'activityId': '3c3a28c9-70aa-455b-8213-7b20465e93be', 'subActivityId': '59d25ff3-6154-47a9-9f90-17309adc8670', 'activityType': 'DN.FE.ExecuteControlCommand', 'parentActivityId': 'fcb91686-ab9d-4e7d-8718-8b7851252831', 'activityStack': '(Activity stack: CRID=KPC.execute;a692efbc-6da9-476c-84a7-10097afbe84a ARID=3c3a28c9-70aa-455b-8213-7b20465e93be > DN.Admin.Client.ExecuteControlCommand/394367cb-4fcd-4148-8f7d-d141e44ac590 > P.WCF.Service.ExecuteControlCommandInternal..IAdminClientServiceCommunicationContract/fcb91686-ab9d-4e7d-8718-8b7851252831 > DN.FE.ExecuteControlCommand/59d25ff3-6154-47a9-9f90-17309adc8670)'}, '@permanent': True}}])`

**Comment by kerend** [comment]
Hi,

The purge command should be executed to the data management service (as ingests do), the service holds a queue of purge command, their status, and retry commands if needed.

All you need to do is to change the cluster parameter to point to the data management service, adding 'ingest-' prefix: "https://ingest-devmetrics.eastus2.kusto.windows.net".

Purge process is explained [here](https://docs.microsoft.com/en-us/azure/kusto/concepts/data-purge)

**Comment by danield137** [comment]
Closing, @kerend answered

**Comment by thisisnish** [comment]
@kerend @danield137 My question was how to execute .purge command programmatically. Surely, you don't expect us to run all purge operations manually. Also, "https://ingest-devmetrics.eastus2.kusto.windows.net" is a windows executable which does not run on Mac. Please advice how to get around above two hurdles.

**Comment by thisisnish** [comment]
Thanks @kerend @danield137
