### ISSUE TITLE
"Syntax error: Query could not be parsed: . Query: '.get ingestion resources'" when running parquet ingestion

### ISSUE THREAD

**Issue by james-tn** [Azure/azure-kusto-python#171]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
client = KustoIngestClient(kcsb)
i=0
for BLOB_PATH in blob_list:
    if i%50==0:
        print(str(i)+":"+BLOB_PATH)
    ingestion_props = IngestionProperties(
        database="HEB",
        table="Orders",
        dataFormat=DataFormat.PARQUET,
        mappingReference ="ordersparquetmapping"
        # incase status update for success are also required
        # reportLevel=ReportLevel.FailuresAndSuccesses,
    )

    blob_descriptor = BlobDescriptor(blob_list[0], 100000)  # 10 is the raw size of the data in bytes.
    client.ingest_from_blob(blob_descriptor, ingestion_properties=ingestion_props)
    i=i+1
print("Done queueing all files")
```
#### Problem description
KustoServiceError: (KustoServiceError(...), [{'error': {'message': 'Request is invalid and cannot be executed.', '@type': 'Kusto.Data.Exceptions.SyntaxException', '@context': {'activityStack': '(Activity stack: CRID=KPC.execute;95c3c526-bc86-4103-957a-61bd9e71c72b ARID=1b4b19a9-9ea6-44f7-a31f-5c1fcbc5085f > DN.Admin.Client.ExecuteControlCommand/a2724130-abe8-46e7-90e7-501b58719343 > P.WCF.Service.ExecuteControlCommandInternal..IAdminClientServiceCommunicationContract/4d754776-c142-4f70-b327-f1eb2c19fb3c > DN.FE.ExecuteControlCommand/4986aaed-731c-4131-99f0-7905f36d4413)', 'appDomainName': 'Kusto.WinSvc.Svc.exe', 'processName': 'Kusto.WinSvc.Svc', 'processId': 3796, 'activityType': 'DN.FE.ExecuteControlCommand', 'timestamp': '2019-10-01T23:39:23.0328157Z', 'threadId': 6296, 'subActivityId': '4986aaed-731c-4131-99f0-7905f36d4413', 'clientRequestId': 'KPC.execute;95c3c526-bc86-4103-957a-61bd9e71c72b', 'machineName': 'KEngine000001', 'activityId': '1b4b19a9-9ea6-44f7-a31f-5c1fcbc5085f', 'parentActivityId': '4d754776-c142-4f70-b327-f1eb2c19fb3c', 'serviceAlias': 'ADXDEMO'}, '@message': "Syntax error: Query could not be parsed: . Query: '.get ingestion resources'", 'code': 'Bad request', '@permanent': True}}])

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]

absl-py==0.8.0
adal==1.2.2
asn1crypto==0.24.0
astor==0.8.0
azure-common==1.1.23
azure-kusto-data==0.0.35
azure-kusto-ingest==0.0.35
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-queue==2.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
conda==4.5.12
cryptography==2.4.2
gast==0.3.0
google-pasta==0.1.7
grpcio==1.23.0
h5py==2.10.0
idna==2.8
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
menuinst==1.4.14
numpy==1.17.2
opt-einsum==3.0.1
protobuf==3.9.1
py4j==0.10.7
pycosat==0.6.3
pycparser==2.19
PyJWT==1.7.1
pyOpenSSL==18.0.0
PySocks==1.6.8
pyspark==2.4.1
python-dateutil==2.8.0
pywin32==223
requests==2.21.0
ruamel-yaml==0.15.46
six==1.12.0
tb-nightly==1.15.0a20190806
termcolor==1.1.0
tf-estimator-nightly==1.14.0.dev2019080601
urllib3==1.24.1
Werkzeug==0.15.6
win-inet-pton==1.0.1
wincertstore==0.2
wrapt==1.11.2

</details>

**Comment by eparizzi** [comment]
@james-tn Did you resolve this? What was the cause? I'm having the exact same issue.

**Comment by Michael-Kuritzky** [comment]
@eparizzi - I encountered the same error, turns out that the problem was that I had forgotten to add an `ingest-` prefix to the cluster name. cf. https://github.com/Azure/azure-kusto-python/issues/175

**Comment by eparizzi** [comment]
> @eparizzi - I encountered the same error, turns out that the problem was that I had forgotten to add an `ingest-` prefix to the cluster name. cf. #175

Yes, I've figured it out. Thanks!
