### ISSUE TITLE
Querying a workspace

### ISSUE THREAD

**Issue by bulkware** [Azure/azure-kusto-python#176]
Hello!

Is it possible to run a Kusto-query to a workspace using this SDK? I have searched everywhere for an answer and tried many different combinations but I always get results like this:

`Entity ID '<Insert_workspace_ID_here>' of kind 'Database' was not found.`

So I suppose this SDK only runs queries against a database. Is workspace a database in this context? Or is there a different SDK for these kind of queries?

I authenticate with AAD application certificate and that part works fine.

Thanks in advance.

**Comment by ArielYehezkely** [comment]
Hi, 

You're right, this SDK is used against Kusto and queries run with database context which is different from Log Analytics workspace.

I assume you are looking for the Log Analytics SDK: 
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/loganalytics/azure-loganalytics

**Comment by bulkware** [comment]
Ok, thank you =)
