### ISSUE TITLE
dataframe_from_result_table throws an exception

### ISSUE THREAD

**Issue by amos-rimon** [Azure/azure-kusto-python#178]
when running command:
`dataframe_from_result_table(example_table.execute('tableName | limit 10')[0])`
an exception occurs:
`KustoResultTable' object has no attribute '_rows`

pip freeze:
adal==1.2.2
asn1crypto==0.24.0
attrs==19.1.0
azure-common==1.1.16
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.1
azure-keyvault==1.1.0
azure-kusto-data==0.0.36
azure-nspkg==3.0.2
azure-storage==0.20.1
azure-storage-common==0.37.1
azure-storage-nspkg==3.1.0
backcall==0.1.0
bleach==3.1.0
cassandra-driver==2.6.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
colorama==0.4.1
cryptography==2.7
ddt==1.1.1
decorator==4.4.0
deepdiff==3.3.0
defusedxml==0.6.0
dslib==0.0.1
elasticsearch==1.5.0
entrypoints==0.3
expiringdict==1.1.4
futures==3.1.1
hyperloglog==0.0.10
idna==2.7
ipykernel==5.1.1
ipython==7.7.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.14.1
Jinja2==2.10.1
json5==0.8.5
jsonpickle==1.2
jsonschema==3.0.1
jupyter-client==5.3.1
jupyter-core==4.5.0
jupyterlab==1.0.4
jupyterlab-server==1.0.0
keyvaultlib==1.1.1
MarkupSafe==1.1.1
mistune==0.8.4
mock==2.0.0
msrest==0.6.10
msrestazure==0.5.0
nbconvert==5.5.0
nbformat==4.4.0
nose==1.3.7
notebook==6.0.0
numpy==1.17.0
oauthlib==3.1.0
pandas==0.25.0
pandocfilters==1.4.2
parso==0.5.1
pbr==5.4.3
pickleshare==0.7.5
pika==0.9.14
prometheus-client==0.7.1
prompt-toolkit==2.0.9
pycparser==2.19
pyformance==0.4
Pygments==2.4.2
PyJWT==1.7.1
pykusto==0.0.4
pymongo==3.8.0
Pympler==0.6
pyOpenSSL==18.0.0
pyrsistent==0.15.4
python-dateutil==2.8.0
pytz==2019.1
pywinpty==0.5.5
pyzmq==18.0.2
redis==2.10.6
requests==2.20.0
requests-oauthlib==1.2.0
retrying==1.3.3
Send2Trash==1.5.0
simplejson==3.3.0
six==1.12.0
sortedcontainers==2.1.0
terminado==0.8.2
testpath==0.4.2
thrift==0.9.2
tornado==6.0.3
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1

**Comment by boazsha** [comment]
Hi,

Trying to install these requirements we get:
`ERROR: pykusto 0.0.4 has requirement azure-kusto-data==0.0.31, but you'll have azure-kusto-data 0.0.36 which is incompatible.`
It seems that the cause is that pykusto is not compatible with the new versions of azure-kusto-data.

Hope this helps

**Comment by amos-rimon** [comment]
pykusto is a package we created, that uses azure-kusto-python.
I ran it without it, and it persists.

**Comment by boazsha** [comment]
With the aforementioned reqs installed (other than pykusto), and running the following code with Python3.7, we could not recreate the error:
```python
clientEngine = KustoClient(kcsb)
queryResult = clientEngine.execute('tempDB', 'tableName | limit 10')[0]
df = helpers.dataframe_from_result_table(queryResult)
```

I would suggest creating a clean environment, separating the method calls and validating the responses (maybe posting them here so we might help).
If any errors appear, please paste them with their full stack trace.
Do notice that `database` is a mandatory parameter for `execute()`.

**Comment by amos-rimon** [comment]
looks like it was an issue with my notebook's kernel, a restart solved it.

Thanks!
