### ISSUE TITLE
Query .show operation using azure kusto for python

### ISSUE THREAD

**Issue by kpyszczek** [Azure/azure-kusto-python#179]
Hi, 
I was wondering, if it is possible to run this query using your library:
".show operation <oeprationid> details"
in order to get the path, where our exported data is stored on cloud storage.
I tried it in common way, but it is not working.
Please support.
query=".show operation operationid details"
        response = client.execute(db, query)
        for row in response.primary_results[0]:
            print("value at 0 {}".format(row[0]))
            print("\n")
            print("Path:{}".format(row["Path"]))

**Comment by ArielYehezkely** [comment]
Hi @kpyszczek , 

It is possible to run this query this way, your code sample is working for me. 
Can you please elaborate what is not working? What is the error you get? 
Can you please share your `pip freeze` results? 

Thanks, 
Ariel

**Comment by kpyszczek** [comment]
Hi Ariel,

I would like to export query data on cloud storage and then check the path, where the data is stored and build logic app using this path.
First part is done, I built successfully the export azure func. Results are stored on my blob container.
Please see results:
[cid:image001.png@01D58E2C.E58F80F0]

But when I tried to call the query with command:
.show operation <operation Id> details

The array is empty.
Please see logs and my azure func:
[cid:image002.png@01D58E2D.952155C0]

[cid:image003.png@01D58E2E.10883760]

[cid:image004.png@01D58E2E.10883760]

Func is started using localhost (func host start).
The same query I can run on my kusto explorer and results are printed below:

[cid:image005.png@01D58E2E.29C45470]
Thank you for your help.
Best regards,
Kasia

**Comment by kpyszczek** [comment]
Hi,

please be informed, that now it is working.
I can run only operation id, which has been created on localhost, not via kusto explorer.
Best regards,
Kasia

From: Pyszczek, Katarzyna
Sent: Dienstag, 29. Oktober 2019 07:55
To: 'Azure/azure-kusto-python'; Azure/azure-kusto-python
Cc: Mention
Subject: RE: [Azure/azure-kusto-python] Query .show operation using azure kusto for python (#179)

Hi Ariel,

I would like to export query data on cloud storage and then check the path, where the data is stored and build logic app using this path.
First part is done, I built successfully the export azure func. Results are stored on my blob container.
Please see results:
[cid:image001.png@01D58E2F.A737D980]

But when I tried to call the query with command:
.show operation <operation Id> details

The array is empty.
Please see logs and my azure func:
[cid:image002.png@01D58E2F.A737D980]

[cid:image003.png@01D58E2F.A737D980]

[cid:image004.png@01D58E2F.A737D980]

Func is started using localhost (func host start).
The same query I can run on my kusto explorer and results are printed below:

[cid:image005.png@01D58E2F.A737D980]
Thank you for your help.
Best regards,
Kasia

**Comment by ArielYehezkely** [comment]
Thanks @kpyszczek, Can we close this issue or you need further assistance?

**Comment by kpyszczek** [comment]
Yes, you can close it.
Thanks
Kasia
