### ISSUE TITLE
Exception: The package azure-storage-blob is required. Please install it using "pip install azure-storage-blob" even I've installed the package already

### ISSUE THREAD

**Issue by tehsiuhuang** [Azure/azure-kusto-python#181]
#### Code Sample, a copy-pastable example if possible

  1 import sys
  2
  3 if len (sys.argv) != 3 :
  4     print "Usage: python "+sys.argv[0]+" <kusto Table name> <file to Ingest>"
  5     sys.exit (1)
  6
  7 from azure.kusto.data.request import KustoConnectionStringBuilder
  8 from azure.kusto.ingest import (
  9         KustoIngestClient,
 10         IngestionProperties,
 11         FileDescriptor,
 12         BlobDescriptor,
 13         StreamDescriptor,
 14         DataFormat,
 15         ReportLevel,
 16         KustoStreamingIngestClient,
 17 )
 18
 19 ##################################################################
 20 ##                              AUTH                            ##
 21 ##################################################################
 22 # xxxxx.southcentralus.kuto.windows.net is the url
 23 # ingest-acckusto.southcentralus.kuto.windows.net is the ingestion endpoint
 24 cluster = "https://ingest-xxxxxxx.southcentralus.kusto.windows.net"
 25
 26 databaseName = "ACCTEST"
 27
 28 # Another connect approach which requires user to provide information
 29 # kcsb = KustoConnectionStringBuilder(cluster)
 30 # Authenticate with AAD application.
 31
 32 client_id = "xxxxxxxxxxxxxxxxxxx"
 33 client_secret = "xxxxxxxxxxxxxxxxxxx"
 34 authority_id = "xxxxxxxxxxxxxxxxxxx"
 35
 36
 37 kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(
 38     cluster, client_id, client_secret, authority_id
 39 )
 40
 41 client = KustoIngestClient(kcsb)
 42
 43 ##################################################################
 44 ##                                                                                      INGESTION                             ##
 45 ##################################################################
 46
 47 ingestion_props = IngestionProperties(
 48     database="xxxxx",
 49     table="xxxx",
 50     dataFormat=DataFormat.CSV,
 51     # incase status update for success are also required
 52     reportLevel=ReportLevel.FailuresAndSuccesses,
 53 )
 54
 55 client.ingest_from_file(sys.argv[2], ingestion_properties=ingestion_props)

#### Problem description

Always got exception due to missing azure-storage-blob even I've installed it already.

  File "./lightIngest.py", line 55, in <module>
    client.ingest_from_file(sys.argv[2], ingestion_properties=ingestion_props)
  File "/home/tehuang/.local/lib/python2.7/site-packages/azure/kusto/ingest/_ingest_client.py", line 94, in ingest_from_file
    blob_service = storage_client.create_block_blob_service()
  File "/home/tehuang/.local/lib/python2.7/site-packages/azure/storage/common/cloudstorageaccount.py", line 72, in create_block_blob_service
    + 'Please install it using "pip install azure-storage-blob"')
Exception: The package azure-storage-blob is required. Please install it using "pip install azure-storage-blob"

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

N/A

#### Output of ``pip freeze`` 

<details>

adal==1.2.2
asn1crypto==0.24.0
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-common==1.1.23
azure-core==1.0.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.48
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-kusto-data==0.0.37
azure-kusto-ingest==0.0.37
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.6.2
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.7.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.2.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==12.0.0
azure-storage-common==2.1.0
azure-storage-nspkg==3.1.0
azure-storage-queue==12.0.0
certifi==2019.9.11
cffi==1.13.1
chardet==3.0.4
cryptography==2.8
enum34==1.1.6
futures==3.3.0
idna==2.8
ipaddress==1.0.23
isodate==0.6.0
keyring==10.6.0
keyrings.alt==3.0
msrest==0.6.10
msrestazure==0.6.2
oauthlib==3.1.0
pathlib2==2.3.5
pycparser==2.19
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.7.1
python-dateutil==2.8.0
pyxdg==0.25
requests==2.22.0
requests-oauthlib==1.2.0
scandir==1.10.0
SecretStorage==2.3.1
six==1.12.0
typing==3.7.4.1
urllib3==1.25.6

</details>

**Comment by danield137** [comment]
Please try and align you azre-storage libraries. as you can see in your requirements, you have
```
azure-storage-blob==12.0.0
azure-storage-common==2.1.0
azure-storage-nspkg==3.1.0
azure-storage-queue==12.0.0
```

please try to reinstall them and install again on the same version (2.1.0) as such:
```
pip uninstall azure-storage-blob azure-storage-common azure-storage-nspkg azure-storage-queue
pip install azure-storage-blob==2.1.0 azure-storage-common==2.1.0 azure-storage-queue==2.1.0
```

**Comment by yifan90** [comment]
Have the same problem here yesterday, solve it by install the old version.

The file names in the latest release of azure-storage-blob and azure-storage-queue (released on Oct 31) are completely different from previous versions...

**Comment by danield137** [comment]
Hi @yifan90 , thanks for confirming. I'll lock the versions in the setup.py.
