### ISSUE TITLE
Bump version of dependency on azure-storage-blob to 12.0.0

### ISSUE THREAD

**Issue by cjbackman** [Azure/azure-kusto-python#186]
`ERROR: azure-kusto-ingest 0.0.38 has requirement azure-storage-blob==2.1.0, but you'll have azure-storage-blob 12.0.0 which is incERROR: azure-kusto-ingest 0.0.38 has requirement azure-storage-blob==2.1.0, but you'll have azure-storage-blob 12.0.0 which is incompatible.ompatible.`

**Comment by danield137** [comment]
Hi @cjbackman , we currently don't support azure-storage v12, as they did a lot of breaking changes we need to align to.
It will require some work to do so, and we will get to it in the future, but currently the hard version lock is there for a reason.

I apologize for the inconvenience, I know this is annoying and we are working internally on improving this.

**Comment by eparizzi** [comment]
@danield137 Any updates on this? Would you accept some help on this?

**Comment by danield137** [comment]
If you are willing to go ahead and adjust our code to the latest version of azure-storage, I'm all for it!
