### ISSUE TITLE
Multiple authentications might be triggered due to race condition

### ISSUE THREAD

**Issue by ymost** [Azure/azure-kusto-python#208]
#### Code Sample, a copy-pastable example if possible

```python
from azure.kusto.data.request import KustoClient, KustoConnectionStringBuilder
from threading import Thread
CLUSTER = 'https://help.kusto.windows.net'
client = KustoClient(KustoConnectionStringBuilder.with_aad_device_authentication(CLUSTER))
Thread(target=lambda: client.execute('Samples', 'StormEvents | take 1', None)).start()
res = client.execute('Samples', 'StormEvents | take 1', None)
```

Result: two authentications are triggered.

#### Problem description

For every `KustoClient` instance, the first call to execute triggers an authentication. In case of multiple threads using the same instance, a race condition might occur where multiple authentications are triggered. This is especially pronounced in device authentication, as in the example above, but the same issue can occur with every type of authentication.
Expected behavior: while an authentication is in progress, all further calls to execute should block, and then continue running once the authentication is complete.

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

Not query related.

#### Output of ``pip freeze`` 

<details>

adal==1.2.2
attrs==19.3.0
azure-kusto-data==0.0.44
backcall==0.1.0
bleach==3.1.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
colorama==0.4.3
cryptography==2.8
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
easygui==0.98.1
entrypoints==0.3
idna==2.8
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.16.0
Jinja2==2.11.1
jira==2.0.0
json5==0.9.0
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.2.1
mcasdslib==0.0.11
mistune==0.8.4
msrest==0.6.11
msrestazure==0.6.3
nbconvert==5.6.1
nbformat==5.0.4
notebook==6.0.3
numpy==1.18.1
oauthlib==3.1.0
pandas==1.0.3
pandocfilters==1.4.2
parso==0.6.1
pbr==5.4.4
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.3
pycparser==2.19
Pygments==2.5.2
PyJWT==1.7.1
pykusto==0.0.12
pyparsing==2.4.6
pyrsistent==0.15.7
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
pywinpty==0.5.7
pyzmq==18.1.1
requests==2.22.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
Send2Trash==1.5.0
six==1.14.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.8
wcwidth==0.1.8
webencodings==0.5.1
zipp==2.1.0

</details>

**Comment by danield137** [comment]
The library was not tested for parallel execution. Also, I'm not sure that Adal is thread safe. We should definitely investigate this.

Will Check and get back to you

**Comment by ymost** [comment]
Thanks! 
Note that we want to avoid triggering multiple simultaneous authentications precisely in order to avoid relying on Adal thread safety.

**Comment by vladikbr** [comment]
We are planning to start work on moving to MSAL. Will investigate whether this is still relevant there.

**Comment by yogilad** [comment]
This still recreates with MSAL.

**Comment by yogilad** [comment]
Discussed with @ArielYehezkely,
While it is possible to make the interactive token acquisition thread safe, the azure-kusto-python itself was not built with concurrency in mind, so other issues may arise.

As a workaround for the specific issue, you may want to invoke the client once with `.show version` command, before making any concurrent calls.

**Comment by vladikbr** [comment]
Please try the latest version (2.0.0)
