### ISSUE TITLE
Suggestion: Set value of x-ms-app header in KustoClient

### ISSUE THREAD

**Issue by mojanas** [Azure/azure-kusto-python#209]
**Is your feature request related to a problem? Please describe.**
I'd like to track how our customers access Kusto from different applications - Power BI, Kusto Explorer, Azure Data Explorer online, etc. All these programs set the value of the `x-ms-app` header that is sent with the request, except for this SDK. 

**Describe the solution you'd like**
Set the header value to something like `KustoPythonSDK` or similar in the `_execute()` method in the `KustoClient` class.
```python
request_headers["x-ms-app"] = "KustoPythonSDK"
```

**Describe alternatives you've considered**
We can set this header using the following code. However, this method relies on our customers including these two lines in their code. Having it in the SDK would be much more reliable and useful to us.
```python
crp = ClientRequestProperties()
crp.application = "KustoPythonSDK"
response = client.execute(db, query, crp)
```

**Additional context**
Examples of other applications' values for `x-ms-app`:

Connector | x-ms-app header value
-- | --
Power Bi | PowerBiConnector
Explorer page/ADX | KusWeb
Kusto Explorer | Kusto.Explorer

**Comment by ArielYehezkely** [comment]
Hi @mojanas,

As this is a SDK and not an application, I don't think the package should set the "x-ms-app" header as this header is used to distinguish between different applications (including different applications that uses the same SDK) . 
As you mentioned, the consumer of the package should set it through ClientRequestProperties. 

Note that we set "x-ms-client-version" to "Kusto.Python.Client:<SDK Version>" for that purpose.

Thanks, 
Ariel Yehezkely
