### ISSUE TITLE
Undefined name KustoStreamMaxSizeExceededError in two files

### ISSUE THREAD

**Issue by cclauss** [Azure/azure-kusto-python#213]
#### Code Sample, a copy-pastable example if possible

#147 deleted the definition of `KustoStreamMaxSizeExceededError` but it is required in two test files.  @ArielYehezkely, Do you know how this should be fixed?

```
/azure-kusto-ingest/tests/test_kusto_streaming_ingest_client.py:161:16: F821 undefined name 'KustoStreamMaxSizeExceededError'
        except KustoStreamMaxSizeExceededError:
               ^
./azure-kusto-ingest/tests/e2e.py:404:12: F821 undefined name 'KustoStreamMaxSizeExceededError'
    except KustoStreamMaxSizeExceededError:
           ^
```

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]

</details>

**Comment by ArielYehezkely** [comment]
Hi @cclauss,

Thanks for notifying, @amshalev removed the first mention from e2e and this PR (#226) will remove the other mention in test_kusto_streaming_ingest_client. 

Thanks, 
Ariel
