### ISSUE TITLE
Unclear message when executing the sample code

### ISSUE THREAD

**Issue by damejovanoski** [Azure/azure-kusto-python#217]
#### Code Sample, a copy-pastable example if possible

```python
from azure.kusto.data.exceptions import KustoServiceError
from azure.kusto.data.request import KustoClient, KustoConnectionStringBuilder, ClientRequestProperties

cluster = ""


client_id = ""
client_secret = ""
authority_id = ""


kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(cluster, client_id,
                                                                            client_secret, authority_id)

client = KustoClient(kcsb)

db = "Samples"
query = "StormEvents | take 10"

response = client.execute(db, query)


```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]

The database and the table doesn't exist for sure since I wanted to check if the auth keys, secret..
work, this error message doesn't help at all since I don't what the problem is.

Run the script and you will get:
Traceback (most recent call last):
  File "script.py", line 21, in <module>
    response = client.execute(db, query)
  File "/home/test.virtualenvs/kusto/lib/python3.6/site-packages/azure/kusto/data/request.py", line 531, in execute
    return self.execute_query(database, query, properties)
  File "/home/test.virtualenvs/kusto/lib/python3.6/site-packages/azure/kusto/data/request.py", line 543, in execute_query
    return self._execute(self._query_endpoint, database, query, None, KustoClient._query_default_timeout, properties)
  File "/home/test.virtualenvs/kusto/lib/python3.6/site-packages/azure/kusto/data/request.py", line 631, in _execute
    raise KustoServiceError([response.json()], response)
  File "/home/test.virtualenvs/kusto/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]
adal==1.2.2
azure-common==1.1.25
azure-kusto-data==0.0.44
azure-kusto-ingest==0.0.44
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-queue==2.1.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
idna==2.9
isodate==0.6.0
msrest==0.6.11
msrestazure==0.6.3
oauthlib==3.1.0
pycparser==2.20
PyJWT==1.7.1
python-dateutil==2.8.1
requests==2.23.0
requests-oauthlib==1.3.0
six==1.14.0
urllib3==1.25.8

</details>

**Comment by damejovanoski** [comment]
After some debugging it seems like the 

In azure/kusto/data/request.py
`        print(response.status_code)
        raise KustoServiceError([response.json()], response)
`
The status_code is 404 and because of that the json() doesn't work I guess.

**Comment by danield137** [comment]
Thanks for reporting. This does seem like an unexpected behaviour from our backend (expected to return the error in a json format).

**Comment by damejovanoski** [comment]
Also, instead of creating a new ticket I have a question regarding the error handling and the python API interface. Any plans on the roadmap in improving this? Current the error messages are just propagated from the server as JSON instead of having proper error messages with proper types. To the regards of the Python API it would be nice to have a proper interfaces for creating tables, running different types of queries instead of just having a generic execute function, that way the handling of results would be different compared with the current way of having the data nested in a structure (instead of a iterable structure).
