### ISSUE TITLE
Query streaming parser: when would it be available? 

### ISSUE THREAD

**Issue by MinKPark** [Azure/azure-kusto-python#218]
Hi there, 
I wonder when the Query output streaming parser will be available. 
my team is using Kusto as one of the data sources for databricks. 
Since the size of query output is too big, results are truncated. 
I looked at the documentation. and it mentioned that there is a plan for the streaming parser. 
I wonder when it would be available. 
At least, I hope that there is an Rest API which can support this. so if there is no python wrapper yet, my team can write up one.

**Comment by danield137** [comment]
We don't have an eta for it. Feel free to go ahead and contribute. 
@vladikbr for tracking

**Comment by AsafMah** [comment]
Added in 3.0.0
