### ISSUE TITLE
No support for azure-storage-blob >= 12.0.0 in azure-kusto-ingest 

### ISSUE THREAD

**Issue by kopytjuk** [Azure/azure-kusto-python#225]
#### Problem description

Currently the `azure-kusto-ingest` locked the `azure-storage-blob` package to `2.1.0`. See [here](https://github.com/Azure/azure-kusto-python/blob/ae884820157090f88fc582494f6ad469c5e96d96/azure-kusto-ingest/setup.py#L40) for the corresponding line.

Would it be possible to drop that requirement and raise the version?

**Comment by danield137** [comment]
We cannot drop the requirement as they changed the API. 
We will release a newer version of the Kusto SDK which will point at storage 12.x.x.

Will update this issue with ETA

**Comment by damejovanoski** [comment]
> We cannot drop the requirement as they changed the API.
> We will release a newer version of the Kusto SDK which will point at storage 12.x.x.
> 
> Will update this issue with ETA

Any timeline about when this is planned to be released?

**Comment by danield137** [comment]
I'm getting around to it now, @damejovanoski , so next couple of weeks probably. Maybe sooner.

**Comment by ArielYehezkely** [comment]
Now supported in version v0.1.0 - Thanks @danield137!
