### ISSUE TITLE
Streaming ingest throws 404 error

### ISSUE THREAD

**Issue by james-tn** [Azure/azure-kusto-python#244]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
stream_client = KustoStreamingIngestClient(kcsb)

stream_ingestion_props = IngestionProperties(
    database=kusto_db,
    table="test_tbl",
    data_format=DataFormat.CSV,
)


import pandas

fields = ["id", "name", "value"]
rows = [[1, "streaming", 103.3], [2, "streaming2", 109.9]]

df = pandas.DataFrame(data=rows, columns=fields)

stream_client.ingest_from_dataframe(df, ingestion_properties=stream_ingestion_props)


```
#### Problem description
Error message returned. 
Note that I already enabled Streaming ingestion in the cluster which took a long time for the cluster to be quarriable. Normal ingestion still works 
[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]
---------------------------------------------------------------------------
KustoServiceError                         Traceback (most recent call last)
<ipython-input-9-d6dc60e97716> in <module>
     14 # ingest from file
     15 file_descriptor = FileDescriptor("stream_ingest.csv", 3333)  # 3333 is the raw size of the data in bytes.
---> 16 stream_client.ingest_from_file(file_descriptor, ingestion_properties=stream_ingestion_props)
     17 # stream_client.ingest_from_file("stream_ingest.csv", ingestion_properties=stream_ingestion_props)
     18 

c:\users\janguy\appdata\local\continuum\miniconda3\envs\dlresearch\lib\site-packages\azure\kusto\ingest\streaming_ingest_client.py in ingest_from_file(self, file_descriptor, ingestion_properties)
     69         stream_descriptor = StreamDescriptor(stream, descriptor.source_id, is_compressed)
     70 
---> 71         self.ingest_from_stream(stream_descriptor, ingestion_properties)
     72 
     73         if stream is not None:

c:\users\janguy\appdata\local\continuum\miniconda3\envs\dlresearch\lib\site-packages\azure\kusto\ingest\streaming_ingest_client.py in ingest_from_stream(self, stream_descriptor, ingestion_properties)
    109             stream,
    110             ingestion_properties.format.name,
--> 111             mapping_name=ingestion_properties.ingestion_mapping_reference,
    112         )

c:\users\janguy\appdata\local\continuum\miniconda3\envs\dlresearch\lib\site-packages\azure\kusto\data\client.py in execute_streaming_ingest(self, database, table, stream, stream_format, properties, mapping_name)
    606             endpoint = endpoint + "&mappingName=" + mapping_name
    607 
--> 608         self._execute(endpoint, database, None, stream, KustoClient._streaming_ingest_default_timeout, properties)
    609 
    610     def _execute(self, endpoint: str, database: str, query: str, payload: io.IOBase, timeout: timedelta, properties: ClientRequestProperties = None):

c:\users\janguy\appdata\local\continuum\miniconda3\envs\dlresearch\lib\site-packages\azure\kusto\data\client.py in _execute(self, endpoint, database, query, payload, timeout, properties)
    651         if payload:
    652             raise KustoServiceError(
--> 653                 "An error occurred while trying to ingest: Status: {0.status_code}, Reason: {0.reason}, Text: {0.text}".format(response), response
    654             )
    655 

KustoServiceError: (KustoServiceError(...), 'An error occurred while trying to ingest: Status: 404, Reason: Not Found, Text: ')

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

<details>

absl-py==0.9.0
adal==1.2.2
applicationinsights==0.11.9
asn1crypto==0.24.0
astor==0.8.0
atari-py==0.2.6
attrs==19.1.0
audioread==2.1.8
ax-platform==0.1.6
azure-common==1.1.25
azure-core==1.5.0
azure-graphrbac==0.61.1
azure-identity==1.3.0
azure-keyvault==4.0.0
azure-keyvault-keys==4.1.0
azure-keyvault-secrets==4.1.0
azure-kusto-data==0.1.0
azure-kusto-ingest==0.1.0
azure-mgmt-authorization==0.60.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-keyvault==2.0.0
azure-mgmt-resource==4.0.0
azure-mgmt-storage==4.0.0
azure-storage-blob==12.3.1
azure-storage-queue==12.1.1
azureml-automl-core==1.1.5.1
azureml-core==1.1.5.5
azureml-dataprep==1.3.5
azureml-dataprep-native==14.1.0
azureml-defaults==1.0.74
azureml-model-management-sdk==1.0.1b6.post1
azureml-pipeline==1.1.5
azureml-pipeline-core==1.1.5
azureml-pipeline-steps==1.1.5
azureml-sdk==1.1.5.1
azureml-telemetry==1.1.5.3
azureml-train==1.1.5
azureml-train-automl==1.0.74.1
azureml-train-automl-client==1.1.5.1
azureml-train-core==1.1.5
azureml-train-restclients-hyperdrive==1.1.5
azureml-widgets==1.0.60
backcall==0.1.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.1
bert-serving-client==1.9.8
bert-serving-server==1.9.8
bleach==3.1.0
blinker==1.4
boto==2.49.0
boto3==1.9.191
botocore==1.12.191
botorch==0.1.4
cachetools==3.1.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle==1.2.1
colorama==0.4.1
configparser==3.7.4
contextlib2==0.5.5
contextvars==2.4
cryptography==2.9.2
cycler==0.10.0
Cython==0.29.13
databricks-connect==5.5.1
decorator==4.4.0
defusedxml==0.6.0
dill==0.3.1.1
distro==1.4.0
docker==4.0.2
docutils==0.15.2
dotnetcore2==2.1.13
entrypoints==0.3
fire==0.2.1
flake8==3.7.9
Flask==1.0.3
fusepy==3.0.1
future==0.18.2
gast==0.2.2
gensim==3.8.1
google-api-core==1.15.0
google-auth==1.14.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
googleapis-common-protos==1.6.0
GPUtil==1.4.0
gpytorch==0.3.6
grpcio==1.27.2
gunicorn==19.9.0
-e git+https://github.com/openai/gym.git@52e66f38081548e38711f51d4439d8bcc136d19e#egg=gym
h5py==2.10.0
idna==2.9
imbalanced-learn==0.6.2
immutables==0.11
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
itsdangerous==1.1.0
jedi==0.15.1
jeepney==0.4.1
Jinja2==2.10.1
jmespath==0.9.4
joblib==0.13.2
json-logging-py==0.2
JsonForm==0.0.2
jsonpickle==1.2
jsonschema==3.0.2
JsonSir==0.0.2
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
kaggle-environments==0.1.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keras2onnx==1.5.2
kiwisolver==1.1.0
Kqlmagic==0.1.107.post1
liac-arff==2.4.0
librosa==0.7.0
lightgbm==2.2.3
llvmlite==0.29.0
lxml==4.4.1
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mleap==0.8.1
msal==1.1.0
msal-extensions==0.1.3
msrest==0.6.10
msrestazure==0.6.1
nbconvert==5.6.0
nbformat==4.4.0
ndg-httpsclient==0.5.1
nimbusml==1.5.0
nose==1.3.7
nose-exclude==0.5.0
notebook==6.0.1
numba==0.45.1
numpy==1.18.1
oauthlib==3.1.0
olefile==0.46
onnx==1.6.0
onnxconverter-common==1.6.0
onnxmltools==1.4.1
onnxruntime-gpu==1.0.0
opencensus==0.7.6
opencensus-context==0.1.1
opencensus-ext-azure==1.0.1
opencv-python==4.1.2.30
opt-einsum==3.1.0
pandas==0.23.4
pandocfilters==1.4.2
parso==0.5.1
pathspec==0.5.9
patsy==0.5.1
pickleshare==0.7.5
Pillow==6.1.0
plotly==4.2.1
pmdarima==1.1.1
portalocker==1.5.2
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.11.4
psutil==5.6.3
py4j==0.10.7
pyarrow==0.11.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycodestyle==2.5.0
pycparser==2.20
pyflakes==2.1.1
pyglet==1.3.2
Pygments==2.4.2
PyJWT==1.7.1
pyodbc==4.0.30
pyOpenSSL==19.1.0
pyparsing==2.4.2
pypiwin32==223
pyreadline==2.1
pyrsistent==0.15.4
PySocks==1.7.1
python-dateutil==2.8.0
Python-EasyConfig==0.1.7
pytz==2019.2
pywin32==224
pywinpty==0.5.5
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.5
requests==2.23.0
requests-oauthlib==1.3.0
resampy==0.2.2
Resource==0.2.1
retrying==1.3.3
rsa==4.0
ruamel.yaml==0.15.89
s3transfer==0.2.1
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
six==1.14.0
skl2onnx==1.4.9
sklearn==0.0
sklearn-pandas==1.7.0
smart-open==1.8.4
SoundFile==0.10.2
soupsieve==1.9.5
statsmodels==0.10.1
tensorboard==2.1.1
tensorboardX==1.9
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
tensorflow-gpu-estimator==2.1.0
tensorflow-hub==0.6.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
tf-estimator-nightly==1.14.0.dev2019080601
torch==1.5.0
torchvision==0.6.0
tornado==6.0.3
traitlets==4.3.2
typing-extensions==3.7.4
urllib3==1.25.8
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
Werkzeug==0.15.6
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.12.1
xlrd==1.2.0

</details>

**Comment by ArielYehezkely** [comment]
Hi @james-tn, 

Thanks for reporting this. When streaming ingestion isn't enabled, the ingest endpoint is not exist and this is the returned error by design. We can make the error prettier though. 

Thanks, 
Ariel

**Comment by james-tn** [comment]
Hey, so you assumed I had not enabled streaming ingestion? I did. 
![image](https://user-images.githubusercontent.com/25941658/84422793-65587800-abd2-11ea-89a3-cc735c456388.png)
