### ISSUE TITLE
looks like the azure-kusto-python is not working in mooncake, need add more fault tolerance code.

### ISSUE THREAD

**Issue by WangAnge** [Azure/azure-kusto-python#248]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is

I'm always frustrated when try to use python login kusto in mooncake,
looks like the azure-kusto-python module is not working in mooncake

**Describe the solution you'd like**

maybe you can add more fault tolerance code.

**Describe alternatives you've considered**

Currently need change the code at 'lib/site-packages/azure/kusto/data/security.py' from: 
CLOUD_LOGIN_URL = "https://login.microsoftonline.com/" 
to 
CLOUD_LOGIN_URL = "https://login.partner.microsoftonline.cn" 
that can be fix the issue with can't not access kusto in mooncake by python.

**Additional context**

![image](https://user-images.githubusercontent.com/3390170/86455807-c0a20400-bd53-11ea-8a8d-d17e0f0bb337.png)

**Comment by ohadbitt** [comment]
Hello
please set the environment variable 'AadAuthorityUri' to the required url
default: 'https://login.microsoftonline.com/'

This is exactly where u looked in the code :)
