### ISSUE TITLE
Data type of the columns changes to String when Importing to Pandas Dataframe 

### ISSUE THREAD

**Issue by vbabu29** [Azure/azure-kusto-python#258]
```python

kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(cluster, client_id, client_secret, authority_id)
client = KustoClient(kcsb)
response = client.execute(db, query)
result_df = dataframe_from_result_table(response.primary_results[0])
print(result_df.info())

Id                               1 non-null object
Timestamp                1 non-null datetime64[ns, UTC]
Col1                           1 non-null object
Col2                           1 non-null object

```
#### Problem description

We have observed that the columns with data types as decimal gets converted to String when imported to a pandas dataframe using dataframe_from_result_table method.

Surprisingly, The columns with data type real does NOT get converted to string. So it seems the issue is with datatype Decimal only.

It looks like the response.primary_results[0] i.e. the KustoResultTable is itself converting the column values to string.

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]
adal==1.2.4
azure-core==1.7.0
azure-identity==1.3.1
azure-kusto-data==1.0.1
azure-kusto-ingest==1.0.1
azure-storage-blob==12.3.2
azure-storage-queue==12.1.2
backcall==0.1.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
colorama==0.4.3
cryptography==3.0
idna==2.10
ipython-genutils==0.2.0
isodate==0.6.0
msal==1.4.2
msal-extensions==0.1.3
msrest==0.6.17
numpy==1.19.1
oauthlib==3.1.0
pandas==1.0.5
pickleshare==0.7.5
portalocker==1.7.1
pycparser==2.20
PyJWT==1.7.1
python-dateutil==2.8.1
pytz==2020.1
pywin32==227
requests==2.24.0
requests-oauthlib==1.3.0
six==1.15.0
urllib3==1.25.10
wincertstore==0.2
</details>

**Comment by ArielYehezkely** [comment]
Hi @vbabu29, 

Thanks for reporting - will fix in #261 .
