### ISSUE TITLE
Support for certificate in the KustoClient constructor

### ISSUE THREAD

**Issue by charlesprakash** [Azure/azure-kusto-python#26]
KustoClient today only supports client id with a key. We need to support client id with a certificate to address the scenarios for which the key doesn't meet the security bar.

**Comment by toshetah** [comment]
Hi Charles,

We will hopefully add this functionality soon. Stay tuned.

Thanks,
Tomer

**Comment by danield137** [comment]
Closing. Please reopen if not resolved.
