### ISSUE TITLE
Need a feature that follows the DB-API to allow for a SQLAlchemy dialect

### ISSUE THREAD

**Issue by zheya08** [Azure/azure-kusto-python#264]
Is there a plan of   [Sql Alchemy connector](https://docs.sqlalchemy.org/en/13/dialects/) for Kusto?

**Comment by vladikbr** [comment]
No, but since Kusto exposes TDS endpoint, you can use https://github.com/m32/sqlalchemy-tds

**Comment by deeTEEcee** [comment]
@zheya08 here's one that seems to work: https://github.com/dodopizza/sqlalchemy-kusto

**Comment by deeTEEcee** [comment]
I encountered kusto recently but it's a bit confusing that the Azure Data Explorer UI supports SQL as well as KQL while client libraries themselves like this one would not.

**Comment by pritesh-shrivastava** [comment]
There is an optional parameter `query_language`, in the ClientRequestProperties class, which can be set to 'csl','kql' or 'sql'. 
To SQL queries from this library, We can create an object of the above class (ClientRequestProperties) & set `query_language` parameter to 'sql'.

Source : https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/request-properties
(The above documentation if for the .NET SDK but its works similarly for the Python SDK as well)
