### ISSUE TITLE
Error masked by a JSON decoder error

### ISSUE THREAD

**Issue by charlesprakash** [Azure/azure-kusto-python#27]
In KustoClient in the `_execute` method, when the `response.status_code` is not equal to `200`, the code [throws an exception](https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/azure/kusto/data/kusto_client.py#L356) converting the response to json format. However in cases where the response is not convertible to json, the original error is masked and a `JSONDecodeError` is thrown.

This should be fixed in such a way that the original error is not masked so that the user can fix their problem.

I have encountered this problem when my application didn't have access to the Kusto cluster. The original response status code was 403.

**Comment by ShevaDas** [comment]
@charlesprakash How did you surface the original error? I'm running into this problem too.

**Comment by charlesprakash** [comment]
@ShevaDas I modified the code in the site_packages to print before it is converted to json.

**Comment by toshetah** [comment]
Hi Guys,

Thanks for reporting, this issue is resolved at version 0.0.6.
The check in that fixed that is https://github.com/Azure/azure-kusto-python/commit/b7c3e16044f2f459d4f7504e5d4512ddb4115d843

If it persists to anyone please open a new issue.

**Comment by charlesprakash** [comment]
@toshetah Looks like the commit link is broken?

**Comment by toshetah** [comment]
It is fixed. Try taking the latest (version 0.0.9)
