### ISSUE TITLE
Long duration queries time out when using the python SDK with Kusto

### ISSUE THREAD

**Issue by RuchaBapat** [Azure/azure-kusto-python#271]
The query which takes some 3 to 7 minutes to run, times out when python 3.8.5 is used and the kusto module/library azure-kusto-data version 1.02.

If we see the query status from Azure data explorer it shows that the query is completed but python script waits for the response and times out.

**Comment by ArielYehezkely** [comment]
Hi @RuchaBapat,

The default query timeout is 4 minutes, you can set a longer timeout through ClientRequestProperties. Please see the [Sample](https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/tests/sample.py) line 110.

Thanks, 
Ariel Yehezkely

**Comment by RuchaBapat** [comment]
Setting up ClientRequestProperties indeed helped us and issue is solved for now. We were missing line **properties.set_option(properties.results_defer_partial_query_failures_option_name, True)** in our code. What is the role of this line? Without this our script fails. 

Thank you for your response and this issue can be closed now. We will comment if we face same issue again.

**Comment by ArielYehezkely** [comment]
Hi @RuchaBapat,

The service has timeout on query requests of 4 minutes, so if you need to execute queries which take longer you need to set this option with longer timeout.
Closing.

Thanks, 
Ariel

**Comment by vijaykvs** [comment]
@ArielYehezkely isn't the purpose of results_defer_partial_query_failures_option_name to suppress any issues in case there are partial query errors in Kusto query execution. I'm somehow not understanding how and why this is tied to timeout setting. If partial query error occurs e.g. in case of OOM issues, query might return partial results. And if this option is set in SDK, we will never know if the results returned are complete or partial. Can you please validate my understanding. Thanks!

**Comment by yihezkel** [comment]
Hi @vijaykvs,

Please see https://docs.microsoft.com/en-us/azure/data-explorer/kusto/concepts/partialqueryfailures for an explanation of what a partial query failure is.

You can see how it works in [azure-kusto-data/tests/test_kusto_client.py in the test method test_partial_results](https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/tests/test_kusto_client.py#L312).

`        properties.set_option(ClientRequestProperties.results_defer_partial_query_failures_option_name, False)
        self.assertRaises(KustoServiceError, client.execute_query, "PythonTest", query, properties)
        properties.set_option(ClientRequestProperties.results_defer_partial_query_failures_option_name, True)
        response = client.execute_query("PythonTest", query, properties)
        assert response.errors_count == 1
        assert "E_QUERY_RESULT_SET_TOO_LARGE" in response.get_exceptions()[0]
        assert len(response) == 3
        results = list(response.primary_results[0])
        assert len(results) == 5
        assert results[0]["x"] == 1
`

Specifically, if results_defer_partial_query_failures_option_name is False, 1 failure will cause the entire execution to return an exception. However, if results_defer_partial_query_failures_option_name is True, the response will be successful with a combination of the successful results, and a list of the failures with their exceptions.

Does this help?
