### ISSUE TITLE
This package requires 'azure.identity>=1.3.1' which doesn't exist

### ISSUE THREAD

**Issue by ephraimbuddy** [Azure/azure-kusto-python#273]
#### Code Sample, a copy-pastable example if possible

```bash
pip install azure-kusto-data

```
#### Problem description

Installing azure-kusto-data in a virtual environment requires 'azure.identity>=1.3.1' but there's no such package. This causes an error of `pkg_resources.DistributionNotFound: The 'azure.identity>=1.3.1' distribution was not found and is required by azure-kusto-data' and truly there's no such package. What is available on pypi is azure-identity

**Comment by ArielYehezkely** [comment]
Hi @ephraimbuddy ,

Thanks for reporting. This issue is fixed now, it will be available in the next version.

**Comment by ephraimbuddy** [comment]
Awesome! Thanks!
