### ISSUE TITLE
Can I use a API KEY to access azure?

### ISSUE THREAD

**Issue by jasminekao** [Azure/azure-kusto-python#276]
I only can get API key for azure, is there a way to access by using API key?

**Comment by ArielYehezkely** [comment]
Hi @jasminekao, 

Can you please elaborate your scenario and what are you trying to achieve?

Please see the docs on how to create a cluster - [Quickstart: Create an Azure Data Explorer cluster and database](https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-portal) 

Thanks, 
Ariel
