### ISSUE TITLE
Intermitten SSL Verification Errors

### ISSUE THREAD

**Issue by brycefisher** [Azure/azure-kusto-python#278]
#### Code Sample, a copy-pastable example if possible

```python
from azure.kusto.data.request import KustoClient, KustoConnectionStringBuilder

kcsb = KustoConnectionStringBuilder.\
            with_aad_application_key_authentication(cluster_url,
                                                    client_id,
                                                    client_secret,
                                                    tenant_id)
client = KustoClient(kcsb)
client.execute_mgmt(db, ".show table T1")
```

Sometimes, non-reproducibly, the above code will raise this exception:

> Traceback (most recent call last):
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/circleci/repo/common/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vde947mediacadx.eastus.kusto.windows.net', port=443): Max retries exceeded with url: /v1/rest/mgmt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

#### Problem description

Since re-running this code again seems to solve the issue, it would be nice to have an option to do retries or barring that some way to get the request ID out. Right now I can't raise an issue with support that's very effective without the request ID. If I had the request ID I could rule out certificate issues on the remote side.

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

Does not seem to depend on the query.

#### Output of ``pip freeze`` 

<details>
adal==1.2.2
attrs==19.3.0
azure-common==1.1.25
azure-core==1.7.0
azure-functions==1.3.0
azure-identity==1.3.0
azure-kusto-data==0.0.33
azure-kusto-ingest==0.0.33
azure-mgmt-kusto==0.5.0
azure-mgmt-resource==8.0.1
azure-mgmt-storage==11.2.0
azure-storage-blob==12.3.2
azure-storage-common==2.1.0
azure-storage-queue==12.1.2
behave==1.2.6
boto3==1.13.10
botocore==1.16.26
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
docopt==0.6.2
docutils==0.15.2
dotty-dict==1.2.1
entrypoints==0.3
flake8==3.7.9
freezegun==0.3.15
google-api-core==1.22.2
google-auth==1.21.1
googleapis-common-protos==1.52.0
hypothesis==5.38.1
idna==2.10
importlib-metadata==1.7.0
isodate==0.6.0
jmespath==0.10.0
mccabe==0.6.1
more-itertools==8.4.0
msal==1.4.1
msal-extensions==0.1.3
msrest==0.6.17
msrestazure==0.6.4
oauthlib==3.1.0
opencensus==0.7.10
opencensus-context==0.1.1
opencensus-ext-azure==1.0.4
packaging==20.4
parse==1.15.0
parse-type==0.5.2
pluggy==0.13.1
portalocker==1.7.1
protobuf==3.13.0
psutil==5.7.2
py==1.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycparser==2.20
pyflakes==2.1.1
PyJWT==1.7.1
pyparsing==2.4.7
pytest==5.4.3
python-dateutil==2.8.1
pytz==2020.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
s3transfer==0.3.3
setuptools-scm==4.1.2
six==1.15.0
sortedcontainers==2.2.2
urllib3==1.25.9
wcwidth==0.2.5
zipp==3.1.0
</details>

**Comment by ArielYehezkely** [comment]
Hi @brycefisher,

This exception comes from urllib3 package, and we have no control whether the error contains the request ID or not, we throw it as is. It looks like the urllib3 package does have retry logic and he exception was thrown after max retries reached.
This package usually doesn't handle retries but I am going to mark this issue as Enhancement, and we will discuss your suggestion internally and update accordingly. 

Thanks, 
Ariel Yehezkely

**Comment by brycefisher** [comment]
@ArielYehezkely thanks for writing back! So, while it's true that this exception is thrown by urllib3, this package could

 - Add a try/except block around the requests invocation that re-raises a new exception with the ClientActivityId added for easier debugging and collaboration with Azure Support. Here's some quick sample code I would place near https://github.com/Azure/azure-kusto-python/blob/3e32efb44438a950aeb5ade828a7f8b86dbed5c1/azure-kusto-data/azure/kusto/data/client.py#L696:

```py
        try:
            response = self._session.post(endpoint, headers=request_headers, data=payload, json=json_payload, timeout=timeout.seconds)
        except urllib3.exceptionos.MaxRetryError as e:
            request_data = {"endpoint": endpoint, "headers": request_headers, "data": payload, "timeout": timeout.seconds}
            raise KustoServiceError("Unable to connect with Kusto Server",  request_data) from e
```


- Expose a means of providing retry logic as part of the public API for this package in the KustoClient or KustoMgmtClient. Right now, I'd have to fork or monkeypatch to leverage the built in retry mechanism. See https://github.com/Azure/azure-kusto-python/blob/3e32efb44438a950aeb5ade828a7f8b86dbed5c1/azure-kusto-data/azure/kusto/data/client.py#L587-L588 - I would rewrite something like this:

```py
    def __init__(self, kcsb: Union[KustoConnectionStringBuilder, str],retries=0):
        # -- snip --
        self._session.mount("http://", HTTPAdapter(pool_maxsize=self._max_pool_size, max_retries=retries))
        self._session.mount("https://", HTTPAdapter(pool_maxsize=self._max_pool_size, max_retries=retries))
```

See requests & urllib docs:
 - https://2.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter
 - https://urllib3.readthedocs.io/en/latest/user-guide.html?highlight=retry#retrying-requests
 - https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Retry

**Comment by ArielYehezkely** [comment]
Hi @brycefisher, 

Thank you for your comments.
1.  KustoServiceError used to wrap exceptions returned from the cluster and this issue is a client side exception, the request did not reach the cluster and the ClientActivityId won't be found during a server side investigation. 
We can wrap the exception with KustoClientError but it won't add information on top of the original exception.

2. Thanks for your suggestion, I think we can expose "max_pool_size" and "retries" to set HTTPAdapter properties. 

Thanks, 
Ariel

**Comment by brycefisher** [comment]
Thanks!! 

 1. Ah, yep, you're right. Thanks!
 2. Great!! Thanks.

**Comment by vladikbr** [comment]
We have also identified a server side issue that could be related: in a rare condition it is possible that some of the machines in the cluster "keep" a leftover SSL cert that gets picked up. In these cases reimaging a node (by our Ops) resolves this type of issues.

**Comment by brycefisher** [comment]
Thanks @vladikbr! Yes, I believe that's how we encountered this situation.

**Comment by matys1** [comment]
This was in 2020. I'm getting this same exact error in 2022. What should I do?

**Comment by brycefisher** [comment]
The problem is the load balancer in Azure has at least one server node with invalid TLS certificate. 

You can:
 - report the issue to ADX support with repro steps and wait
 - try to scale in and out until the bad ADX VM is deleted or entirely recreate the ADX cluster
 - you can fork the python library to disable TLS certificate checking (not advisable because attackers can impersonate Azure)

I started running a script to prove the TLS works on a bunch of dummy queries every time I spin up a new ADX cluster since I was unconvinced Azure had fixed the TLS provisioning bug on their end
