### ISSUE TITLE
Internal docs for querying Kusto using Azure Notebooks appear out of sync

### ISSUE THREAD

**Issue by tleonhardt** [Azure/azure-kusto-python#28]
The [internal docs](https://kusto.azurewebsites.net/docs/tools/tools_azurenotebooks.html) for querying Kusto using Azure Notebooks appear to refer to a different API than is present in your [README.md](https://github.com/Azure/azure-kusto-python/blob/master/README.md).

For example, The interal docs show using this:
```Python
from kusto_client import KustoClient
```

Whereas the README shows this:
```Python
from azure.kusto.data import KustoClient
```

**Comment by zivcaspi** [comment]
+ @Tomer Shetah<mailto:toshetah@microsoft.com>

**Comment by toshetah** [comment]
Thanks Todd for reporting. The internal docs now gives only references to the updated code in GitHub.
