### ISSUE TITLE
Ingest methods should check if `IngestionMapping` exists when using `ingestionMappingReference`

### ISSUE THREAD

**Issue by kopytjuk** [Azure/azure-kusto-python#283]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an exception when using `ingestionMappingReference` without an existing mapping in ADX. If someone accidentally deletes the mapping, the application code does not break ...

**Describe the solution you'd like**
An Exception telling that the `ingestionMappingReference` does not exist.

**Describe alternatives you've considered**
Writing an own query from the application itself to check the existence.

**Additional context**

**Comment by vladikbr** [comment]
The way the APIs work do not require an active connection to the service in time of the ingestion call.
What you can do is to verify the mapping existence prior to making the ingest call.
