### ISSUE TITLE
AdalError thrown when AzCLI refresh token is expired

### ISSUE THREAD

**Issue by alexkyllo** [Azure/azure-kusto-python#286]
**Is your feature request related to a problem? Please describe.**
When authenticating via the `KustoConnectionStringBuilder.with_az_cli_authentication()` method, if the cached Azure CLI refresh token is expired, the package throws an ugly exception trace: `AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity...`

**Describe the solution you'd like**
Instead of throwing this exception, I think the azure-kusto-data package should catch it and display a nice message to the user informing them that their token is expired and what they should do to refresh it (i.e. run `az login`). It *could* also fall back on another method such as device code authentication.

**Additional context**
I write a lot of Jupyter notebooks and data analysis packages that use `KustoConnectionStringBuilder.with_az_cli_authentication()` and would not like to have to write additional error handling code to catch this exception in each notebook to help my users understand what to do when it happens.

**Comment by yogilad** [comment]
PR #293
