### ISSUE TITLE
Class 'DataFormat' has no 'W3CLOGFILE' member...

### ISSUE THREAD

**Issue by ecc256** [Azure/azure-kusto-python#292]
Getting strange error when I try to use `dataFormat=DataFormat.W3CLOGFILE` in `IngestionProperties()`
According to docs it’s supported [1](https://docs.microsoft.com/en-us/azure/data-explorer/ingestion-supported-formats) and [2](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.kusto.models.eventgriddataconnection.dataformat?view=azure-dotnet) already... somehow I’m not able to see it [here](https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-ingest/azure/kusto/ingest/ingestion_properties.py) either?
Does **W3CLOGFILE** have different name in Python SDK?

[Here](https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/azure/kusto/data/data_format.py) is another source file with same formats, yet no sign on W3CLOGFILE still…?

**Comment by ArielYehezkely** [comment]
Hi @ecc256, 

Thanks for pointing this out, you're right the package doesn't support this format yet, I'll add this feature to our tasks list. 

Thanks, 
Ariel Yehezkely

**Comment by ecc256** [comment]
@ArielYehezkely 
Could you suggest a workaround, please?
I've switched to C# SDK for now, but would gladly to switch to anything Python-based instead!
