### ISSUE TITLE
Add support for azure-identity authentication

### ISSUE THREAD

**Issue by empz** [Azure/azure-kusto-python#296]
It should be possible to authenticate using `azure-identity` to better align with other Azure services like storage.

Something like the following:

```python
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder
from azure.identity import DefaultAzureCredential

cluster = "https://clusterurl"
default_credential = DefaultAzureCredential()

kcsb = KustoConnectionStringBuilder.with_azure_identity_credential(cluster, default_credential)

client = KustoClient(kcsb)
```

**Comment by ArielYehezkely** [comment]
Hi @empz, 

Thanks for the suggestion. 
@yogilad WDYT?

**Comment by yogilad** [comment]
It's an interesting package we actually use when for managed identity authentication.
It's possible to add support for this alongside our MSAL implementation, but if you have an immediate need, you can implement this using the with_token_provider() and pass a lambda function which obtains a token to your resource using the identity provider of your choice.

**Comment by vladikbr** [comment]
Postponing for now. This functionality is available with with_token_provider().

**Comment by yihezkel** [comment]
Closing per @vladikbr 's comment above

**Comment by mhangaard** [comment]
@vladikbr how do you use this? Could you point me to some documentation on how to use with_token_provider together with azure.identity credentials classes?

It doesn't seem trivial to me or equivalent to blob storage ect., so I think it would be valuable to reopen this issue and make the funcitonality.

**Comment by FaresKi** [comment]
Hi,
I agree, at least an example on how to do the same thing using `with_token_provider()` 
@mhangaard, any luck hopefully?
TIA

**Comment by mhangaard** [comment]
> Hi,
> I agree, at least an example on how to do the same thing using `with_token_provider()` 
> @mhangaard, any luck hopefully?
> TIA

It works for me with `KustoConnectionStringBuilder`, like shown above.

**Comment by jeffvan98** [comment]
I'm new to this SDK, so please forgive me if I make a mistake, but...  It still (2024) doesn't look like the SDK supports DefaultCredential like empz suggested back in 2021.  I'd like to see an example of what yogilad suggested because mahangaard's suggestion relies on attempting managed service identity before falling back to cli authentication via exception handling.
