### ISSUE TITLE
Add a warning if logged in into multiple organizations

### ISSUE THREAD

**Issue by kopytjuk** [Azure/azure-kusto-python#300]
In https://github.com/Azure/azure-kusto-python/blob/337e4b77116b9316e617a33415068327dc0e6064/azure-kusto-data/azure/kusto/data/_token_providers.py:

```
folder = os.getenv("AZURE_CONFIG_DIR", None) or os.path.expanduser(os.path.join("~", ".azure"))
token_path = os.path.join(folder, "accessTokens.json")
with open(token_path) as f:
    data = json.load(f)

# TODO: not sure I should take the first
return data[0]
```

In case `accessTokens.json` contains multiple tokens, it happens that you grab the wrong credential. Raise a warning in case `data` has multiple elements, s.t. the user can simplify the reason for failed query.

**Comment by ArielYehezkely** [comment]
Hi @kopytjuk, 

Thanks for the suggestion, I'm adding it to out backlog.

**Comment by yogilad** [comment]
@kopytjuk, we had an internal discussion regarding the current implementation.
Bottom line is, it was devised when there was no official integration for az-cli, and it works by delving deep into the private implementation of az.
Today Azure.Identity allows for this authentication mode, therefore we will scrap our private implementation in favor of Azure.Identity.

That being said, Azure.Identity will also return one of the logged in accounts token.
You may control the account being used with the `az account set` command.
More information on az account can be found here: https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest

**Comment by kopytjuk** [comment]
> @kopytjuk, we had an internal discussion regarding the current implementation.
> Bottom line is, it was devised when there was no official integration for az-cli, and it works by delving deep into the private implementation of az.
> Today Azure.Identity allows for this authentication mode, therefore we will scrap our private implementation in favor of Azure.Identity.
> 
> That being said, Azure.Identity will also return one of the logged in accounts token.
> You may control the account being used with the `az account set` command.
> More information on az account can be found here: https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest

Thanks for deep insights into this issue! I am also a fan of consistency by using Azure.Indentity 👍

**Comment by yogilad** [comment]
PR #318
