### ISSUE TITLE
Add support for usgovernment regions kusto 

### ISSUE THREAD

**Issue by amankohli** [Azure/azure-kusto-python#314]
We need support on the module for usgov regions like usgovvirginia,usgovtexas etc

**Comment by vladikbr** [comment]
You actually mean support for sovereign/air-gapped clouds.
We are working on this, as a workaround, you can obtain the token for your Kusto resource yourself and pass it to the with_token_provider method.

**Comment by amankohli** [comment]
Yes I mean support for sovereign/air-gapped clouds. Do we have a timeline when the support will be added to the library?

**Comment by yogilad** [comment]
Versions following change #325 should handle other clouds well.
If there are issues, let us know.
