### ISSUE TITLE
Kusto.Data.Exceptions.KustoBadRequestException', '@message': 'Request is invalid and cannot be processed: Syntax error: SYN0001

### ISSUE THREAD

**Issue by shirelight** [Azure/azure-kusto-python#316]
I'm using Azure Kusto Data to execute some queries. All of the queries run fine on Kusto Explorer, and they are long and complicated ones. However when running the queries with Python Kusto client in Jupyter notebook, for some queries I will get the following traceback and error. However, some execute just fine and I can't tell from the queries what's causing the issue. I can't provide the detailed queries. Here's as much traceback and error message I can provide with project-related info hidden. Any insights or known limitations would be helpful. 

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\azure\kusto\data\client.py in _execute(self, endpoint, database, query, payload, timeout, properties)
    872             response_json = response.json()
--> 873             response.raise_for_status()
    874         except Exception as e:

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 

HTTPError: 400 Client Error: BadRequest for url: https://****.kusto.windows.net//v2/rest/query

The above exception was the direct cause of the following exception:

KustoServiceError                         Traceback (most recent call last)
<ipython-input-28-1e6dc7b8e583> in <module>
----> 1 result = KUSTO_CLIENT.execute(KUSTO_DATABASE, query)
      2 result_df = dataframe_from_result_table(result.primary_results[0])

C:\ProgramData\Anaconda3\lib\site-packages\azure\kusto\data\client.py in execute(self, database, query, properties)
    800         if query.startswith("."):
    801             return self.execute_mgmt(database, query, properties)
--> 802         return self.execute_query(database, query, properties)
    803 
    804     def execute_query(self, database: str, query: str, properties: ClientRequestProperties = None) -> KustoResponseDataSet:

C:\ProgramData\Anaconda3\lib\site-packages\azure\kusto\data\client.py in execute_query(self, database, query, properties)
    812         :rtype: azure.kusto.data.response.KustoResponseDataSet
    813         """
--> 814         return self._execute(self._query_endpoint, database, query, None, self._query_default_timeout, properties)
    815 
    816     def execute_mgmt(self, database: str, query: str, properties: ClientRequestProperties = None) -> KustoResponseDataSet:

C:\ProgramData\Anaconda3\lib\site-packages\azure\kusto\data\client.py in _execute(self, endpoint, database, query, payload, timeout, properties)
    873             response.raise_for_status()
    874         except Exception as e:
--> 875             self._handle_http_error(e, endpoint, payload, response, response_json, response.text)
    876 
    877         return self._kusto_parse_by_endpoint(endpoint, response_json)

C:\ProgramData\Anaconda3\lib\site-packages\azure\kusto\data\client.py in _handle_http_error(exception, endpoint, payload, response, response_json, response_text)
    691 
    692         if response_json:
--> 693             raise KustoServiceError([response_json], response) from exception
    694 
    695         if response_text:

KustoServiceError: [{'error': {'code': 'General_BadRequest', 'message': 'Request is invalid and cannot be executed.', '@type': 'Kusto.Data.Exceptions.KustoBadRequestException', '@message': 'Request is invalid and cannot be processed: Syntax error: SYN0001: I could not parse that, sorry. [line:position=0:0]. Query: .............

**Comment by ArielYehezkely** [comment]
Hi @shirelight,

The error implies its a syntax error so I would look for escaping or other differences between C# (KE) and Python. 
If the information is sensitive you are also welcome to mail me the full error message including the SourceId, timestamp and ClientRequestId so I could look into it.

Thanks,
Ariel Yehezkely

**Comment by shirelight** [comment]
Hi @ArielYehezkely, thanks for the answer. I found a place that matches what you're describing in my query. In the Kusto query I have `columnValue contains "valA\\valB"`, for it to work in Python I need to change it to `columnValue contains "valA\\\\valB"`. I'm yet to identify a full list of differences that need to be paid attention to.

**Comment by ArielYehezkely** [comment]
Hi @shirelight, 

Thanks for the update.
I'm closing this issue for now, please reopen if needed.

Thanks, 
Ariel
