### ISSUE TITLE
requests.exceptions.ConnectionError:Max retries exceeded with url: /v2/rest/query 

### ISSUE THREAD

**Issue by yiquliu** [Azure/azure-kusto-python#319]
Hi team,
The problem I met is similar to this one: [Issue115](https://github.com/Azure/azure-kusto-python/issues/115). However, I'm using 2.1.0, and upgrading does not work for me.

Error message says:
MaxRetryError: HTTPSConnectionPool(host='azscperf.westus.kusto.windows.net', port=443): Max
 retries exceeded with url: /v2/rest/query (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection
object at 0x0000023468BBEC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

This does not happen every time, but occasionally. 

Thanks!!

**Comment by ohadbitt** [comment]
Doesn't seem related to client code
Googling, i found this:
https://stackoverflow.com/questions/7334199/getaddrinfo-failed-what-does-that-mean
specifically:
The problem, in my case, was that some install at some point defined an environment variable http_proxy on my machine when I had no proxy.

Removing the http_proxy environment variable fixed the problem.

**Comment by ohadbitt** [comment]
Hey 
is the issue resolved?

**Comment by yihezkel** [comment]
As we haven't received an update in almost a month, we're going to close this. Please feel free to reopen as needed.
