### ISSUE TITLE
MSAL Dep Pin causing installation issues 

### ISSUE THREAD

**Issue by dciborow** [Azure/azure-kusto-python#333]
#### Problem description

the current python pin of msal==1.9.0 conflicts with another microsoft package we are using, "commondatamodel-objectmodel". We are also requesting they loosen their pin as well.

**Comment by tzvika-microsoft** [comment]
We're also experiencing problems due to this issue.
Note: the current requirement is "msal~=1.9.0"
Maybe this could be changed to "msal~=1.9" which would allow more flexibility, while still not auto upgrading to 2.*

**Comment by AsafMah** [comment]
Closed with version 2.3.1, please re-open if there's a problem.
