### ISSUE TITLE
Kusto SDK is dependent on Azure-Identity 1.5.0. Please bump it to at least Azure-identity 1.6.0

### ISSUE THREAD

**Issue by manuchandel** [Azure/azure-kusto-python#336]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

Azure-Identity 1.6.0 provides a new way to authenticate client using certificate data. Azure-Identity 1.5.0 requires a certificate to be present in file on the cluster. 

Storing certificates is not recommended. Hence we are using Azure-identity 1.6.0 to read certificate bytes from memory.

But we cannot use 1.6.0 version because azure-kusto has a dependency on Azure-Identity 1.5.0.

This is causing us to store certificate data on the disk. Please bump the requirement to Azure-Identity 1.6.0

#### Output of ``pip freeze`` 

```
Installing collected packages: azure-identity, azure-kusto-data
  Attempting uninstall: azure-identity
    Found existing installation: azure-identity 1.6.0
    Uninstalling azure-identity-1.6.0:
      Successfully uninstalled azure-identity-1.6.0
Successfully installed azure-identity-1.5.0 azure-kusto-data-2.3.0
```

**Comment by AsafMah** [comment]
Closed with version 2.3.1, please re-open if there's a problem.
