### ISSUE TITLE
aiohttp dependency is too old in azure-kusto-data

### ISSUE THREAD

**Issue by tzvika-microsoft** [Azure/azure-kusto-python#337]
#### Problem description

azure-kusto-data has "aiohttp~=3.4.4" dependency, which is dated to 2018.
Since then there were a lot of bug fixes and enhancements to the package, 
please allow us to use aiohttp 3.* or at least 3.7.*
Currently we are experiencing this  [aiohttp bug](https://github.com/aio-libs/aiohttp/issues/3298), but I'm sure there are a lot of other known bugs and old dependencies which are forced with this version.

Thanks!

**Comment by AsafMah** [comment]
Closed with version 2.3.1, please re-open if there's a problem.
