### ISSUE TITLE
Async client exception while handling aio response status

### ISSUE THREAD

**Issue by tzvika-microsoft** [Azure/azure-kusto-python#338]
#### Code section, from azure/kusto/data/client.py:681

```python
def _handle_http_error(
        exception: Exception,
        endpoint: Optional[str],
        payload: Optional[io.IOBase],
        response: "Union[Response, aiohttp.ClientResponse]",
        response_json: Any,
        response_text: Optional[str],
    ) -> NoReturn:
        if response.status_code == 404:
            if payload:
                raise KustoServiceError("The ingestion endpoint does not exist. Please enable streaming ingestion on your cluster.", response) from exception
```
#### Problem description

When `_handle_http_error` receives an aiohttp.ClientResponse, there's an exception because ClientResponse doesn't have a `status_code` attribute, in aiohttp it is `status`.

**Comment by AsafMah** [comment]
What version are you on? 
This was fixed a while back

**Comment by tzvika-microsoft** [comment]
Apologies, I was on v 2.1.1, now that I've updated to 2.3.1 I can see it is resolved.
Thanks for the fast response!
