### ISSUE TITLE
Question: Support for 'render' operator

### ISSUE THREAD

**Issue by xTEddie** [Azure/azure-kusto-python#346]
Does this support using 'render' operator to render charts/graphs? 

If yes, is there any examples?

**Comment by yogilad** [comment]
Rendering is a client side operation supported natively by Kusto Explorer and Kusto Web Explorer.
Kusto Web Explorer also has a Dashboards feature.
Our SDKs do not include a rendering capability on their own.

**Comment by zyw400** [comment]
Dear team,

I wonder if there is any change to this question? Our team is looking into a similar request for the development of a chatbot for DRI.

Regards,

Yiwen
