### ISSUE TITLE
Int/float columns with nulls/NaNs are not converted correctly to Pandas types in dataframe_from_result_table()

### ISSUE THREAD

**Issue by janlugt** [Azure/azure-kusto-python#347]
#### Copy-pastable Code Sample

```python
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder
from azure.kusto.data.helpers import dataframe_from_result_table

url = '[redacted]'
authority_id = '[redacted]'
client_id = '[redacted]'
client_secret = '[redacted]'
db_name = '[redacted]'
kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(
    url, client_id, client_secret, authority_id)
client = KustoClient(kcsb)

query = """range intValue from 0 to 5 step 1
    | extend floatValue = todouble(intValue) / 10
    | extend intValueWithNull = iff(intValue == 2, int(null), intValue)
    | extend floatValueWithNull = iff(intValue == 2, double(null), floatValue)
    | extend floatValueWithNan = iff(intValue == 2, 0.0/0.0, floatValue)
    | extend floatValueWithInf = iff(intValue == 2, 1.0/0.0, floatValue)
    | extend floatValueWithNegInf = iff(intValue == 2, -1.0/0.0, floatValue)
    """

res = client.execute(db_name, query)
df = dataframe_from_result_table(res.primary_results[0])
print(df.dtypes)
```
This yields four incorrect dtypes:
```
intValue                  int64
floatValue              float64
intValueWithNull        float64  # wrong
floatValueWithNull      float64
floatValueWithNan        object  # wrong
floatValueWithInf        object  # wrong
floatValueWithNegInf     object  # wrong
dtype: object
```
#### Problem description
What I would expect here is that Pandas' native support for nulls and nans is used here. Instead, nans and infinities come in as strings, making the column have the object dtype, which requires postprocessing before it can be useful. Since there is some postprocessing based on column_type already in dataframe_from_result_table(), it would be nice if ints and floats can be processed as well, on top of the existing functionality for bools, dates and timespans. I wasn't able to make ADX return a negative zero value, which I believe is the last IEEE754 special value.

As a suggestion, this is how the columns can be fixed:
```
df['intValueWithNull'] = df['intValueWithNull'].astype('Int64')
df['floatValueWithNan'] = df['floatValueWithNan'].replace('NaN', np.NaN).astype('Float64')
df['floatValueWithInf'] = df['floatValueWithInf'].replace('Infinity', np.PINF).astype('Float64')
df['floatValueWithNegInf'] = df['floatValueWithNegInf'].replace('-Infinity', np.NINF).astype('Float64')
```
Int columns with missing values have to be cast to Int64, for float columns, they can become either Float64 or float64. In case Pandas' Float64 is preferred over NumPy's float64, the NumPy types can also be cast:
```
df['intValue'] = df['intValue'].astype('Int64')
df['floatValue'] = df['floatValue'].astype('Float64')
df['floatValueWithNull'] = df['floatValueWithNull'].astype('Float64')
```

I'm happy to create a pull request for this change, using either Pandas or NumPy datatypes.

#### Output of ``pip freeze`` 

<details>
azure-kusto-data==2.3.2

numpy==1.21.4
pandas==1.3.4
</details>

**Comment by ArielYehezkely** [comment]
Hi @janlugt ,

Thanks for reporting, please see the attached PR.

**Comment by janlugt** [comment]
That looks great! I tested this with my example code, and these are the types that get returned, all as expected:
```
intValue                  Int64
floatValue              Float64
intValueWithNull          Int64
floatValueWithNull      Float64
floatValueWithNan       Float64
floatValueWithInf       Float64
floatValueWithNegInf    Float64
dtype: object
```
Do you prefer the new Pandas dtypes as well? This might be an interface change. It seems to be the way forward when it comes to Pandas (vs. exposing NumPy types). For every example, except intValueWithNull, the NumPy types could still be used, but I think it's nice to be consistent and always use the new types. There are always .to_numpy() functions in Pandas objects for people who need arrays with NumPy types.

**Comment by janlugt** [comment]
Thanks a lot for the fast resolution!

**Comment by janlugt** [comment]
One more question here: is the 2.4.0 release already planned, and if so, when will that happen?
