### ISSUE TITLE
Error when executing ingesting of multiple files

### ISSUE THREAD

**Issue by ntomczek** [Azure/azure-kusto-python#35]
Receive the following error when attempting to process multiple local csv files:

`Bad request: Request is invalid and cannot be executed. Entity ID '[DB NetDefaultDB v?.?]' of kind 'Database' was not found.`

I'm passing my DB name as the database I'm connecting to so I searched the azure-kusto-ingest source and found that the first place that NetDefaultDB is used in the process is the _get_temp_storage_objects function:

```
def _get_temp_storage_objects(self):
        response = self._kusto_client.execute_mgmt("NetDefaultDB", ".create tempstorage")
        storages = list()
        for row in response.iter_all():
            storages.append(_ConnectionString.parse(row["StorageRoot"]))
        return storages
```

The execute management function first variable is the DB. Since the "NetDefaultDB" is a string I'm not sure if this is this part of Kusto's inner working for ingestion and this error is permission related or if this value is supposed to be a variable related to the DB actually being accessed.

**Comment by toshetah** [comment]
@ntomczek , can you please share your code snippet?
Please note that your kusto_cluster should be:
https://**ingest**-clustername.kusto.windows.net

**Comment by danield137** [comment]
Closing. Please reopen if not resolved.
