### ISSUE TITLE
"dataframe_from_result_table" fails to handle out-of-range datetimes.

### ISSUE THREAD

**Issue by liamkirton** [Azure/azure-kusto-python#355]
Kusto datetimes start from "0001-01-01 00:00:00.0", whereas Pandas start from "1677-09-21 00:12:43.145224193". As a consequence, dataframe_from_result_table raises an Exception when Kusto returns out-of-range datetimes.

The following KQL will reproduce:

```
let T = datatable(a:datetime, b:string) [
    datetime(0001-01-01), "foo"
];
T | take 1;
```

The fix should be simply adding `errors="coerce"` to the datetime conversion in dataframe_from_result_table.

**Comment by yogilad** [comment]
@ArielYehezkely , @AsafMah , do you see any objection to the change?

If not, @liamkirton could you please add a test for the change and we'll accept the contribution.
Thanks!

**Comment by liamkirton** [comment]
Thanks @yogilad - I've updated with PR and added `tests/test_helpers.py `, to exercise `dataframe_from_result_table`. Really happy to address any additional comments!

**Comment by yogilad** [comment]
Added @AsafMah & @ArielYehezkely  to handle review

**Comment by AsafMah** [comment]
Merged
