### ISSUE TITLE
Add principal for aadapps does not set appid properly

### ISSUE THREAD

**Issue by vilit1** [Azure/azure-kusto-python#365]
The add-principal command does not properly set the appid as seen when adding a principal using the azure portal.

#### Code Sample, a copy-pastable example if possible

```python
az kusto database add-principal --cluster-name <cluster> --database-name <database> -g <rg> --value role="Admin" email="" type="App" name="nameofapp" app-id="AAAAAAAAAAAAAAAAAA" fqn="aadapp=BBBBBBBBBBBBBBBBBBBBB;TTTTTTTTTTTTTTTTT"

```
#### Problem description
The expected appId should be AAAAAAAAAAAAAAAAAA from the above example, but I get BBBBBBBBBBBBBBBBBBBBB instead.

If this step is done through the azure portal and the principals are listed the appId correctly shows as AAAAAAAAAAAAAAAAAA. Is the CLI or the portal correct?

#### Output of ``az version``
 az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "255.255.12",
    "kusto": "0.3.0"
  }
}

#### Output of ``pip freeze`` 

adal==1.2.7
alabaster==0.7.12
antlr4-python3-runtime==4.7.2
applicationinsights==0.11.7
argcomplete==1.11.1
asn1crypto==0.24.0
astroid==2.8.6
atomicwrites==1.4.0
attrs==21.4.0
azdev==0.1.36
azure-appconfiguration==1.1.1
azure-batch==11.0.0
-e git+https://github.com/vilit1/azure-cli.git@78f15dd339ef17afe0b357b77d9c0ba19b14ef2a#egg=azure_cli&subdirectory=src\azure-cli
-e git+https://github.com/vilit1/azure-cli.git@78f15dd339ef17afe0b357b77d9c0ba19b14ef2a#egg=azure_cli_core&subdirectory=src\azure-cli-core
-e git+https://github.com/vilit1/azure-cli.git@78f15dd339ef17afe0b357b77d9c0ba19b14ef2a#egg=azure_cli_telemetry&subdirectory=src\azure-cli-telemetry
-e git+https://github.com/vilit1/azure-cli.git@78f15dd339ef17afe0b357b77d9c0ba19b14ef2a#egg=azure_cli_testsdk&subdirectory=src\azure-cli-testsdk
azure-common==1.1.22
azure-core==1.21.1
azure-cosmos==3.2.0
azure-datalake-store==0.0.49
azure-graphrbac==0.60.0
azure-identity==1.6.1
azure-iot==255.255.12
azure-iot-device==2.9.0
azure-keyvault==1.1.0
azure-keyvault-administration==4.0.0b3
azure-keyvault-keys==4.5.0b4
azure-loganalytics==0.1.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==0.2.0
azure-mgmt-appconfiguration==2.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==0.61.0
azure-mgmt-batch==16.0.0
azure-mgmt-batchai==7.0.0b1
azure-mgmt-billing==6.0.0
azure-mgmt-botservice==0.3.0
azure-mgmt-cdn==11.0.0
azure-mgmt-cognitiveservices==13.0.0
azure-mgmt-compute==23.1.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==9.1.0
azure-mgmt-containerregistry==8.2.0
azure-mgmt-containerservice==16.1.0
azure-mgmt-core==1.3.0
azure-mgmt-cosmosdb==7.0.0b2
azure-mgmt-databoxedge==1.0.0
azure-mgmt-datalake-analytics==0.2.1
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==10.0.0
azure-mgmt-deploymentmanager==0.2.0
azure-mgmt-devtestlabs==4.0.0
azure-mgmt-dns==8.0.0
azure-mgmt-eventgrid==9.0.0
azure-mgmt-eventhub==9.1.0
azure-mgmt-extendedlocation==1.0.0b2
azure-mgmt-hdinsight==9.0.0
azure-mgmt-imagebuilder==0.4.0
azure-mgmt-iotcentral==9.0.0b1
azure-mgmt-iothub==2.1.0
azure-mgmt-iothubprovisioningservices==1.0.0
azure-mgmt-keyvault==9.3.0
azure-mgmt-kusto==0.3.0
azure-mgmt-loganalytics==11.0.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-maps==2.0.0
azure-mgmt-marketplaceordering==1.1.0
azure-mgmt-media==7.0.0
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==0.2.0
azure-mgmt-netapp==5.1.0
azure-mgmt-network==19.3.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.0.0
azure-mgmt-privatedns==1.0.0
azure-mgmt-rdbms==10.0.0
azure-mgmt-recoveryservices==2.0.0
azure-mgmt-recoveryservicesbackup==3.0.0
azure-mgmt-redhatopenshift==1.0.0
azure-mgmt-redis==13.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.6.0
azure-mgmt-resource==20.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==2.0.0b1
azure-mgmt-servicebus==6.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-servicefabricmanagedclusters==1.0.0
azure-mgmt-servicelinker==1.0.0b1
azure-mgmt-signalr==1.0.0b2
azure-mgmt-sql==3.0.1
azure-mgmt-sqlvirtualmachine==1.0.0b1
azure-mgmt-storage==19.0.0
azure-mgmt-synapse==2.1.0b2
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==4.0.0
azure-multiapi-storage==0.7.0
azure-nspkg==3.0.2
azure-storage-blob==12.9.0
azure-storage-common==1.4.2
azure-synapse-accesscontrol==0.5.0
azure-synapse-artifacts==0.10.0
azure-synapse-managedprivateendpoints==0.3.0
azure-synapse-spark==0.2.0
Babel==2.9.1
bcrypt==3.2.0
black==21.12b0
certifi==2021.10.8
cffi==1.15.0
cfgv==3.3.1
chardet==3.0.4
charset-normalizer==2.0.10
click==8.0.3
colorama==0.4.4
ConfigArgParse==1.5.3
coverage==6.2
cryptography==36.0.1
Deprecated==1.2.13
deprecation==2.1.0
distlib==0.3.4
docutils==0.18.1
execnet==1.9.0
fabric==2.4.0
filelock==3.4.2
flake8==4.0.1
gitdb==4.0.9
GitPython==3.1.25
humanfriendly==10.0
identify==2.4.2
idna==3.3
imagesize==1.3.0
iniconfig==1.1.1
invoke==1.2.0
isodate==0.6.1
isort==5.10.1
janus==1.0.0
javaproperties==0.5.1
Jinja2==2.11.3
jmespath==0.9.5
jsondiff==1.3.0
jsonschema==3.2.0
knack==0.9.0
lazy-object-proxy==1.7.1
MarkupSafe==1.1.1
mccabe==0.6.1
msal==1.16.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
multidict==5.2.0
mypy-extensions==0.4.3
Naked==0.1.31
nodeenv==1.6.0
oauthlib==3.1.1
packaging==21.3
paho-mqtt==1.6.1
paramiko==2.6.0
pathspec==0.9.0
pbr==5.3.1
pkginfo==1.8.2
platformdirs==2.4.1
pluggy==1.0.0
portalocker==1.7.1
pre-commit==2.16.0
psutil==5.8.0
py==1.11.0
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
PyGithub==1.55
Pygments==2.11.2
PyJWT==2.3.0
pylint==2.11.1
PyNaCl==1.4.0
pyOpenSSL==21.0.0
pyparsing==3.0.6
pyreadline3==3.3
pyrsistent==0.18.0
PySocks==1.7.1
pytest==6.2.5
pytest-cov==3.0.0
pytest-env==0.6.2
pytest-forked==1.4.0
pytest-mock==3.6.1
pytest-rerunfailures==10.2
pytest-xdist==2.5.0
python-dateutil==2.8.2
pytz==2021.3
pywin32==302
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.0
requests-unixsocket==0.3.0
responses==0.16.0
scp==0.13.2
semver==2.13.0
shellescape==3.8.1
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
Sphinx==1.6.7
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-websupport==1.2.4
sshtunnel==0.1.5
tabulate==0.8.9
toml==0.10.2
tomli==1.2.3
tox==3.24.5
tqdm==4.62.3
typing_extensions==4.0.1
uamqp==1.5.0
urllib3==1.26.8
vcrpy==4.1.1
virtualenv==20.13.0
vsts==0.1.25
wcwidth==0.1.7
websocket-client==0.56.0
wrapt==1.13.3
xmltodict==0.12.0
yarl==1.7.2

**Comment by AsafMah** [comment]
I'm not sure how this issue is related to this sdk, as it seems to be an issue with azure cli.
Try in https://github.com/Azure/azure-cli.

I'm closing it for now, please re-open if you can explain the relevance.
