### ISSUE TITLE
Connection string with dSTS Federation Security 

### ISSUE THREAD

**Issue by ahmad-masalha** [Azure/azure-kusto-python#374]
I'd like to query kusto cluster whose connection string contains the key:

> "dSTS Federated Security=True"

.
The connection string looks like: 'Data Source=https://cluster.kusto.cloud.net;dSTS Federated Security=True'
but I receive the following exception: KeyError: 'dsts federated security'.

I can find support for AAD Fed only, which fails on authorization:

 ```
try:
        kusto_client = KustoClient(KustoConnectionStringBuilder.with_az_cli_authentication('Data Source=https://cluster.kusto.cloud.net;fed=True')
    except Exception as ex:
        print(ex)
```

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cluster.kusto.cloud.net/v2/rest/query

**Comment by yogilad** [comment]
@ahmad-masalha , I'm closing this item.
If you have found a way to obtain a dSTS token, contact me via email.
