### ISSUE TITLE
Create Kusto client using federated identity credential without using any app secret

### ISSUE THREAD

**Issue by prmahajan** [Azure/azure-kusto-python#388]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder
KCSB_DATA = KustoConnectionStringBuilder.with_aad_application_key_authentication(KUSTO_DATA_URI, CLIENT_ID, CLIENT_SECRET, AUTHORITY_ID)
ingest_data = KustoClient(KCSB_DATA)
KCSB_INGEST = KustoConnectionStringBuilder.with_aad_application_key_authentication(KUSTO_INGEST_URI, CLIENT_ID, CLIENT_SECRET, AUTHORITY_ID)
ingest_client = QueuedIngestClient(KCSB_INGEST)
```
#### Problem description

I'm trying to connect to Azure Data Explorer (ADX/ Kusto) from Azure Kubernetes Service (AKS) pod. Is there any way to create Kusto client using AAD application Authentication by providing federated identity credential but without using any app secret(CLIENT_SECRET) in python?

**Comment by yogilad** [comment]
Yes. 
You can use Managed Identities with AKS as described here: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

To authenticate with a managed identity attached to your AKS use `with_aad_managed_service_identity_authentication(kustoUri)` if the system managed identity is used, or `with_aad_managed_service_identity_authentication(kustoUri, client_id: miClientId)` if a user assigned MI is used.

**Comment by prmahajan** [comment]
We are using Azure AD Workload Identity which does not support Managed identities. Is there any way to use AAD Application Authentication without using any app secret(CLIENT_SECRET)?
