### ISSUE TITLE
Error after upgrading azure-identity to version 1.9.0

### ISSUE THREAD

**Issue by ltlopes** [Azure/azure-kusto-python#395]
After upgrading azure-identity to version 1.9.0, KustoClient returns error related to ManagedIdentityCredential when using App Service Managed Identity.

#### Code Sample:

```python
from azure.kusto.data import KustoConnectionStringBuilder
from azure.kusto.data.aio import KustoClient
from azure.kusto.data.exceptions import KustoApiError
import logging

logger = logging.getLogger(__name__)

async def execute_kusto_query(query, timeout):
    KUSTO_CLUSTER = <data_explorer_kusto_cluster>
    APP_OBJECT_ID = <app_object_id>
    AAD_TENANT_ID = <aad_tenant_id>
    KCSB = KustoConnectionStringBuilder.with_aad_managed_service_identity_authentication(KUSTO_CLUSTER, client_id=APP_OBJECT_ID, timeout=timeout)
    KCSB.authority_id = AAD_TENANT_ID
    KUSTO_DATABASE = <data_explorer_database>
    try:
        async with KustoClient(KSCB) as client:
            response = await client.execute(KUSTO_DATABASE, query)    
    except KustoApiError:
        logger.exception("ERROR: ")        
    return response

```
#### Problem description

Code was working as expected when using a Python 3.9.7 AppService with azure-identity version 1.8.0. Service logs shows it has got the credentials successfully:

> 2022-04-20T19:54:17.185623371Z 2022-04-20 19:54:17,185 [40] INFO: ManagedIdentityCredential will use App Service managed identity
> 2022-04-20T19:54:17.190457631Z 2022-04-20 19:54:17,190 [40] INFO: Request URL: 'http://169.254.130.2:8081/msi/token?api-version=REDACTED&resource=REDACTED&clientid=REDACTED'
> 2022-04-20T19:54:17.190504931Z Request method: 'GET'
> 2022-04-20T19:54:17.190511031Z Request headers:
> 2022-04-20T19:54:17.190515331Z     'secret': 'REDACTED'
> 2022-04-20T19:54:17.190519831Z     'User-Agent': 'azsdk-python-identity/1.8.0 Python/3.9.7 (Linux-5.4.0-1063-azure-x86_64-with-glibc2.28)'
> 2022-04-20T19:54:17.190524131Z No body was attached to the request
> 2022-04-20T19:54:17.204723707Z 2022-04-20 19:54:17,204 [40] INFO: Response status: 200
> 2022-04-20T19:54:17.204771408Z Response headers:
> 2022-04-20T19:54:17.204776608Z     'Date': 'Wed, 20 Apr 2022 19:54:16 GMT'
> 2022-04-20T19:54:17.204780808Z     'Content-Type': 'application/json; charset=utf-8'
> 2022-04-20T19:54:17.204784908Z     'Server': 'Kestrel'
> 2022-04-20T19:54:17.204799508Z     'Transfer-Encoding': 'chunked'
> 2022-04-20T19:54:17.210214976Z 2022-04-20 19:54:17,209 [40] INFO: AppServiceCredential.get_token succeeded
> 2022-04-20T19:54:17.211086886Z 2022-04-20 19:54:17,210 [40] INFO: ManagedIdentityCredential.get_token succeeded

However, after upgrading to azure-identity version 1.9.0, service starts to fail acquiring credentials:

> 2022-04-20T19:59:22.426172244Z 2022-04-20 19:59:22,425 [41] INFO: ManagedIdentityCredential will use App Service managed identity
> 2022-04-20T19:59:22.437654118Z 2022-04-20 19:59:22,437 [41] INFO: Request URL: 'http://169.254.130.3:8081/msi/token?api-version=REDACTED&resource=REDACTED&client_id=REDACTED'
> 2022-04-20T19:59:22.437720018Z Request method: 'GET'
> 2022-04-20T19:59:22.437726718Z Request headers:
> 2022-04-20T19:59:22.437730518Z     'X-IDENTITY-HEADER': 'REDACTED'
> 2022-04-20T19:59:22.437734118Z     'User-Agent': 'azsdk-python-identity/1.9.0 Python/3.9.7 (Linux-5.4.0-1063-azure-x86_64-with-glibc2.28)'
> 2022-04-20T19:59:22.437737718Z No body was attached to the request
> 2022-04-20T19:59:22.577653319Z 2022-04-20 19:59:22,577 [41] INFO: Response status: 400
> 2022-04-20T19:59:22.577683119Z Response headers:
> 2022-04-20T19:59:22.577688019Z     'Date': 'Wed, 20 Apr 2022 19:59:21 GMT'
> 2022-04-20T19:59:22.577691519Z     'Content-Type': 'application/json; charset=utf-8'
> 2022-04-20T19:59:22.577695019Z     'Server': 'Kestrel'
> 2022-04-20T19:59:22.577698319Z     'Transfer-Encoding': 'chunked'
> 2022-04-20T19:59:22.580989740Z 2022-04-20 19:59:22,578 [41] WARNING: AppServiceCredential.get_token failed: (None) No UserAssigned Managed Identity found for specified ClientId/ResourceId/PrincipalId.
> 2022-04-20T19:59:22.581009040Z Code: None
> 2022-04-20T19:59:22.581013340Z Message: No UserAssigned Managed Identity found for specified ClientId/ResourceId/PrincipalId.
> 2022-04-20T19:59:22.582049347Z 2022-04-20 19:59:22,581 [41] WARNING: ManagedIdentityCredential.get_token failed: (None) No UserAssigned Managed Identity found for specified ClientId/ResourceId/PrincipalId.
> 2022-04-20T19:59:22.582063247Z Code: None
> 2022-04-20T19:59:22.582067247Z Message: No UserAssigned Managed Identity found for specified ClientId/ResourceId/PrincipalId.
> 

Apparently there is a difference in request headers, probably related to msi token's api-version. The first request sends key 'secret' on header while the second sends 'X-IDENTITY-HEADER'.

**Comment by yogilad** [comment]
We can't help much with Azure.Identity issues.
You should contact Azure Identity on their Repo for any behavioral changes.

That said, you code implies you pass the MI object id to the client Id parameter `client_id=APP_OBJECT_ID`.
Please be sure to pass the MI client id and not the object Id.
