### ISSUE TITLE
Error "KustoBlobError: The value for one of the HTTP headers is not in the correct format" with 12.13.0 version azure-storage-blob

### ISSUE THREAD

**Issue by ND0101** [Azure/azure-kusto-python#404]
Below simple code will be failed due to the error "KustoBlobError: The value for one of the HTTP headers is not in the correct format".

```python
from azure.kusto.data import KustoConnectionStringBuilder
from azure.kusto.ingest import (
    QueuedIngestClient,
    IngestionProperties
)

kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication("INGEST_URI", ID, KEY, "TENANT_ID")
client = QueuedIngestClient(kcsb)

ingestion_props = IngestionProperties(
    database="DATABASE",
    table="TABLE"
)
client.ingest_from_dataframe(pandas_df, ingestion_properties = ingestion_props)

```

But If I force to install the previously version of azure-storage-blob with version 12.12.0. The ingest will be succ.

**Comment by AsafMah** [comment]
I can't confirm the error - can you provide more information? 
Maybe other packages installed, a full stacktrace, etc.

**Comment by ND0101** [comment]
I cannot re-produce the error either. Looks like there was some service side issue. Closed the issue.
