### ISSUE TITLE
Noisy ingest example

### ISSUE THREAD

**Issue by mathaholic** [Azure/azure-kusto-python#411]
#### Problem statement

on https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-ingest/tests/sample.py

there are three mentions of an optional noisy fail using
```    # report_level=ReportLevel.FailuresAndSuccesses,```
in the ingestion properties.

ReportLevel is not in the import lines.   Might make a better tutorial if you include an import of ReportLevel, so I don't have to the source code to figure this out.

**Comment by AsafMah** [comment]
Thank you - fixed
