### ISSUE TITLE
How can complex queries be automatically converted?

### ISSUE THREAD

**Issue by GonzaloMurillo** [Azure/azure-kusto-python#421]
**Is your feature request related to a problem? Please describe.**
In your example, the queries are very simple, like
query = "StormEvents | take 10"

But I am working with difficult queries that spread several lines and need to be put in string format and escaping every character

**Describe the solution you'd like**
A method to convert a query to its string equivalent, escaping all the required characters.

**Comment by yogilad** [comment]
You can use query parameters for that .
See: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/queryparametersstatement?pivots=azuredataexplorer#examples.

You should declare the parameters in the query literal as below and use ClientRequestProperty set_parameter() API to pass the value.
Kusto will handle the escaping for you.

```
declare query_parameters(UserName:string, Password:string);
print n=UserName, p=hash(Password)
```
