### ISSUE TITLE
Add support to MSAL package

### ISSUE THREAD

**Issue by kfirberger** [Azure/azure-kusto-python#422]
**Add support to [MSAL](https://pypi.org/project/msal/) package**

We want to upgrade from [ADAL](https://pypi.org/project/adal/) to [MSAL](https://pypi.org/project/msal/), we don't use ADAL directly in our code, but we do initialize SecretClient object from [azure.keyvault.secrets](https://pypi.org/project/azure-keyvault-secrets/) package. It turns out that even the latest version of [azure.keyvault.secrets](https://pypi.org/project/azure-keyvault-secrets/) uses ADAL through using another package [msrestazure](https://pypi.org/project/msrestazure/).

Can you add support to MSAL packages or/and make sure that ADAL won't be included even as external dependency?

**Example:** 
_File "...", line 6, in <module>
  from azure.keyvault.secrets import SecretClient
  File "...\.venv\lib\site-packages\azure\keyvault\__init__.py", line 25, in <module>
  from .key_vault_client import KeyVaultClient
  File "...\.venv\lib\site-packages\azure\keyvault\key_vault_client.py", line 14, in <module>
  from msrestazure.azure_active_directory import BasicTokenAuthentication
  File "...\.venv\lib\site-packages\msrestazure\azure_active_directory.py", line 38, in <module>
  import adal_

**Comment by yogilad** [comment]
@kfirberger , are you sure this is addressed to us (Kusto)?
We no longer take a direct dependency on ADAL and you state "but **we** do initialize SecretClient object from **azure.keyvault.secrets**".

**Comment by kfirberger** [comment]
Hi, I'm not sure who should handle this, I don't know what the ownership model is. But we use latest version of azure.keyvault.secrets and eventually it causes to import ADAL to our virtual environment as explained in imports example.

Who do you think should handle this, break this chain of  azure.keyvault.secrets -> msrestazure -> ADAL?

**Comment by yogilad** [comment]
You can start here: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-secrets

**Comment by yihezkel** [comment]
I see someone had a similar issue in that repo, and they closed it with a comment that might help you too:
https://github.com/Azure/azure-sdk-for-python/issues/24948#issuecomment-1163783593

**Comment by yogilad** [comment]
@kfirberger , you should take this with key vault per the repo I pointed you to.
