### ISSUE TITLE
Loading all data in a dataframe

### ISSUE THREAD

**Issue by jccarrascog** [Azure/azure-kusto-python#423]
Hi all,

I am new in Kusto and I am not sure if this is already implemented since I am not able to find a solution anywhere. I am querying data from a database but I only get 21485 rows when using:

`df = dataframe_from_result_table(response.primary_results[0])`

There is more data available. In Kusto Desktop I can navigate to the next page but it does not seem possible here. Is it possible to extract a whole month of data independently of the volume? I mean 8 GB or similar.

Thanks in advance.

**Comment by yogilad** [comment]
Can you clarify your scenario further?
What happens if you run the query as is?

**Comment by ohadbitt** [comment]
If your query returns multiple tables in the desktop you will get multiple tabs and here you have primary_results is a collection of KustoResultTable but includes only primary ones.
Other tables are iterable on the response object itself

For reference:
https://github.com/Azure/azure-kusto-python/blob/435192e11bb9221532c136c1ae631004ed505874/azure-kusto-data/azure/kusto/data/response.py#L77
