### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED when client is under security endpoints

### ISSUE THREAD

**Issue by kbeaugrand** [Azure/azure-kusto-python#426]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
KCSB = KustoConnectionStringBuilder.with_aad_device_authentication(KUSTO_CLUSTER)
KCSB.authority_id = AAD_TENANT_ID

KUSTO_CLIENT = KustoClient(KCSB)
KUSTO_QUERY = "sequence |take 10"
```
#### Problem description

When executing this sample code I observe an issue on the HTTPs connection : 
```
HTTPSConnectionPool(host='*****.kusto.windows.net', port=443):  ..... SSELCertVerifictionError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] .....
```

I know that the customer where I'm working is using a security endpoint software that is intercepting HTTPS packets and sending them to an internal proxy. 
On the response, the proxy is using a custom certificate (that is trusted by the Windows Machine) to cipher and sign the packets before sending them to the client... 
The issue I have is then quite "normal" and not dependent to this library. 

The question is, **how can we use this library to specify at the connection that the HTTP connection should not verify the certificate issuer from the service?**

**Comment by yogilad** [comment]
Version 3.1.0 includes an option to explicitly set the proxy for such cases.

**Comment by matys1** [comment]
> Version 3.1.0 includes an option to explicitly set the proxy for such cases.

Given my code looks like below:

```
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder

cluster = "cluster_url"
client_id = "app_id"
client_secret = "app_key"
authority_id = "tenant_id"

kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(cluster, client_id, client_secret, authority_id)
client = KustoClient(kcsb)

db = "db"
query = "query"

response = client.execute(db, query)
for row in response.primary_results[0]:
    print(row[0], " ", row["column_name"])
```

Where and how would I set the proxy? The issue is that my company uses Zscaler and with Internet Security turned off I'm able to execute the above query but with Internet Security on I get the SSL cert error.

**Comment by kbeaugrand** [comment]
> Version 3.1.0 includes an option to explicitly set the proxy for such cases.

Hi, 

The question was not about configuring the proxy. It was about specifying the certificate store tu use while connecting to SSL endpoints or more for debugging situation, how to not verify the SSL certificate coming from the server?
