### ISSUE TITLE
pipreqs chooses azure storage 0.37.0 meta pacakge which is depercated (and will not install)

### ISSUE THREAD

**Issue by mbryantII** [Azure/azure-kusto-python#428]
#### Code Sample, a copy-pastable example if possible

```
python3 -m venv .venv
source .venv/bin/activate
pip install azure-kusto-data
pipreqs ./
pip install -r ./requiremts.txt
```
#### Problem description

pipreqs by default is choosing the storage meta package which is deprecated. - I am unsure which storage package to select to ensure I get all of the required packages.

#### Output of ``pip freeze`` 

<details>

azure-core==1.26.0
azure-identity==1.11.0
azure-kusto-data==3.1.3
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==38.0.3
idna==3.4
ijson==3.1.4
msal==1.20.0
msal-extensions==1.0.0
numpy==1.23.4
pandas==1.5.1
portalocker==2.6.0
pycparser==2.21
PyJWT==2.6.0
python-dateutil==2.8.2
pytz==2022.6
requests==2.28.1
six==1.16.0
typing_extensions==4.4.0
urllib3==1.26.12

</details>

**Comment by yogilad** [comment]
Hi @mbryantII ,
Closing this item.
If you have additional details to provide or repro steps, feel free to reopen.
