### ISSUE TITLE
Loss of boolean data in DataFrame conversion

### ISSUE THREAD

**Issue by GCCoding314** [Azure/azure-kusto-python#436]
Similar problem (and fix) for #347 and #349, but for `bool` types.

A Kusto query can return boolean data with True, False and missing data, but the function `dataframe_from_result_table` (helpers.py) performs a type cast of boolean columns to the python `bool` type which supports only `True` and `False`, forcing missing data to the `False` type.

Can this be changed to type cast into the pandas `"boolean"` type, which supports `True`, `False` and `pd.NA`?

    for col in table.columns:
        if col.column_type == "bool":
            frame[col.column_name] = frame[col.column_name].astype(bool)
        elif col.column_type == "int":

would be changed to

    for col in table.columns:
        if col.column_type == "bool":
            frame[col.column_name] = frame[col.column_name].astype("boolean")
        elif col.column_type == "int":

**Comment by AsafMah** [comment]
Added a flag to the function to handle this case in 4.0.1.
Will probably be the default in the next breaking release.
Let us know if you encounter further errors.
