### ISSUE TITLE
KustoConnectionStringBuilder does not deserialize "msi authentication" and "msi params" correctly

### ISSUE THREAD

**Issue by creste** [Azure/azure-kusto-python#439]
#### Code Sample, a copy-pastable example if possible

This code:
```python
kcsb = KustoConnectionStringBuilder.with_aad_managed_service_identity_authentication(
        connection_string=connection_string,
        client_id=client_id)
connection_string = str(kcsb)
client = KustoClient(connection_string)
```
Throws this exception:
```
KeyError: 'msi authentication'
```
#### Problem description

`KustoConnectionStringBuilder` serializes `ValidKeywords.msi_auth` and `ValidKeywords.msi_params` using these keys:
  * MSI Authentication
  * MSI Params

See:
https://github.com/Azure/azure-kusto-python/blob/5405e81d2225b099238240dbbe2176bf616e7308/azure-kusto-data/azure/kusto/data/kcsb.py#L33-L34

When deserializing, only these keys are allowed:
  * msi_auth
  * msi_params
 
See:
https://github.com/Azure/azure-kusto-python/blob/5405e81d2225b099238240dbbe2176bf616e7308/azure-kusto-data/azure/kusto/data/kcsb.py#L68-L71

This fixes the problem:
```diff
diff --git a/azure-kusto-data/azure/kusto/data/kcsb.py b/azure-kusto-data/azure/kusto/data/kcsb.py
index 3289964..b7a9a87 100644
--- a/azure-kusto-data/azure/kusto/data/kcsb.py
+++ b/azure-kusto-data/azure/kusto/data/kcsb.py
@@ -65,9 +65,9 @@ class KustoConnectionStringBuilder:
                 return cls.application_token
             if key in ["user token", "usertoken", "usrtoken"]:
                 return cls.user_token
-            if key in ["msi_auth"]:
+            if key in ["msi_auth", "msi authentication"]:
                 return cls.msi_auth
-            if key in ["msi_type"]:
+            if key in ["msi_params", "msi params"]:
                 return cls.msi_params
             if key in ["az cli"]:
                 return cls.az_cli
```

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]

</details>

**Comment by AsafMah** [comment]
Released in 4.0.2
