### ISSUE TITLE
TypeError when calling dataframe_from_result_table(response.primary_results[0]) on specific python and pandas versions

### ISSUE THREAD

**Issue by ydagli** [Azure/azure-kusto-python#447]
#### Code Sample

```python
from azure.kusto.data import KustoClient, KustoConnectionStringBuilder
from azure.kusto.data.helpers import dataframe_from_result_table

cluster = "https://help.kusto.windows.net"
kcsb = KustoConnectionStringBuilder.with_aad_device_authentication(cluster)
client = KustoClient(kcsb)

db = "Samples"
query = "StormEvents | take 10"

response = client.execute(db, query)

dataframe = dataframe_from_result_table(response.primary_results[0])

print(dataframe)
```
#### Problem description

The error occurs when trying to convert the response table to a pandas dataframe for specific python and pandas versions (in this example for python 3.8.x and pandas 1.1.x), which are default package versions in AML. 

Specifically, the error occurs as the 'Float64', 'Int64', 'Int32' strings are not recognized as np.dtype.

> Traceback (most recent call last):
  File "c:/bug_report/bug_report.py", line 13, in <module>
    dataframe = dataframe_from_result_table(response.primary_results[0])
  File "C:\Users\ydagli\Anaconda3\envs\kusto_bug\lib\site-packages\azure\kusto\data\helpers.py", line 61, in dataframe_from_result_table
    frame[col.column_name] = pd.to_numeric(frame[col.column_name], errors="coerce").astype("Float64")
  File "C:\Users\ydagli\Anaconda3\envs\kusto_bug\lib\site-packages\pandas\core\generic.py", line 5548, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "C:\Users\ydagli\Anaconda3\envs\kusto_bug\lib\site-packages\pandas\core\internals\managers.py", line 604, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\ydagli\Anaconda3\envs\kusto_bug\lib\site-packages\pandas\core\internals\managers.py", line 409, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\ydagli\Anaconda3\envs\kusto_bug\lib\site-packages\pandas\core\internals\blocks.py", line 548, in astype
    dtype = pandas_dtype(dtype)
  File "C:\Users\ydagli\Anaconda3\envs\kusto_bug\lib\site-packages\pandas\core\dtypes\common.py", line 1763, in pandas_dtype
    npdtype = np.dtype(dtype)
TypeError: data type 'Float64' not understood

#### Suggestion: 

My suggestion is to change the 'Float64', 'Int64', 'Int32' strings in the dataframe_from_result_table() function to np.dtypes like np.float64, np.int64, np.int32, which would resolve the problem and would also be stable for other versions of pandas, numpy and python. 

Reference to the pandas astype method documentation (this suggests using numpy.dtype values):
[Pandas astpye](https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.DataFrame.astype.html)
Reference to the numpy documentation:
[Numpy Dtypes](https://numpy.org/doc/1.21/reference/arrays.scalars.html#built-in-scalar-types)

#### Output of ``conda list`` 

<details>

| Name               | Version     | Build          | Channel |
|--------------------|-------------|----------------|---------|
| azure-core         | 1.26.2      | pypi_0         | pypi    |
| azure-identity     | 1.12.0      | pypi_0         | pypi    |
| azure-kusto-data   | 4.0.2       | pypi_0         | pypi    |
| ca-certificates    | 2022.10.11  | haa95532_0     |         |
| certifi            | 2022.12.7   | py38haa95532_0 |         |
| charset-normalizer | 3.0.1       | pypi_0         | pypi    |
| cryptography       | 39.0.0      | pypi_0         | pypi    |
| idna               | 3.4         | pypi_0         | pypi    |
| ijson              | 3.2.0.post0 | pypi_0         | pypi    |
| libffi             | 3.4.2       | hd77b12b_6     |         |
| msal               | 1.20.0      | pypi_0         | pypi    |
| msal-extensions    | 1.0.0       | pypi_0         | pypi    |
| numpy              | 1.21.6      | pypi_0         | pypi    |
| openssl            | 1.1.1s      | h2bbff1b_0     |         |
| pandas             | 1.1.5       | pypi_0         | pypi    |
| pip                | 22.3.1      | py38haa95532_0 |         |
| portalocker        | 2.6.0       | pypi_0         | pypi    |
| pyjwt              | 2.6.0       | pypi_0         | pypi    |
| python             | 3.8.15      | h6244533_2     |         |
| pytz               | 2022.7.1    | pypi_0         | pypi    |
| pywin32            | 305         | pypi_0         | pypi    |
| requests           | 2.28.2      | pypi_0         | pypi    |
| setuptools         | 65.6.3      | py38haa95532_0 |         |
| sqlite             | 3.40.1      | h2bbff1b_0     |         |
| typing-extensions  | 4.4.0       | pypi_0         | pypi    |
| urllib3            | 1.26.14     | pypi_0         | pypi    |
| vc                 | 14.2        | h21ff451_1     |         |
| vs2015_runtime     | 14.27.29016 | h5e58377_2     |         |
| wheel              | 0.37.1      | pyhd3eb1b0_0   |         |
| wincertstore       | 0.2         | py38haa95532_2 |         |

</details>

**Comment by AsafMah** [comment]
Fixed in 4.1.1
