### ISSUE TITLE
Syntax error: SYN0001 despite it working on the Kusto query editor online

### ISSUE THREAD

**Issue by FaresKi** [Azure/azure-kusto-python#451]
#### Code Sample, a copy-pastable example if possible

```py
## modules.py
def match_regex_query(fields: list, regex_patterns: list, kusto_client):
        def match_regex_statements(field, regex_patterns):
            return " or ".join(list(map(lambda pattern: f"{field} matches regex \"{pattern}\"", regex_patterns)))

        count_regex_statement = list(map(
            lambda field: f"count_matching_regex_{field} = countif({match_regex_statements(field, regex_patterns)}), count_not_empty_{field} = countif(isnotempty({field}))", fields))
        count_regex_statement = ", ".join(count_regex_statement)
        summarize_sum_statement = list(map(lambda field: f"Matching_{field} = sum(count_matching_regex_{field}), NotEmpty_{field} = sum(count_not_empty_{field})", fields))
        summarize_sum_statement = ", ".join(summarize_sum_statement)
        project_ratio_statement = list(map(lambda field: f"ratio_{field} = todouble(Matching_{field})/todouble(Matching_{field}+NotEmpty_{field})", fields))
        project_ratio_statement = ", ".join(project_ratio_statement)
        project_round_statement = list(map(lambda field: f"ratio_{field} = iff(isnan(ratio_{field}),0.0,round(ratio_{field}, 3))", fields))
        project_round_statement = ", ".join(project_round_statement)
        query = f"""
        StormEvents
        | where ingestion_time() > ago(1h)
        | summarize {count_regex_statement}
        | summarize {summarize_sum_statement}
        | project {project_ratio_statement}
        | project {project_round_statement}
        """
        clean_query = query.replace("\n", " ").strip()
        try:
            result = kusto_client.execute_query("your_db", clean_query)
        except Exception as err:
            logging.exception(
                f"Error while computing regex metric : {err}")
            result = []
        return result

## main.py

#provide your kusto client here
kusto_client = ...
fields = ["State"]
regex_patterns = ["[A-Z]*"]

metrics = match_regex_query(fields, regex_patterns, kusto_client)
```
#### Problem description

I'm building queries in Python using the method above and executing them on my Kusto clusters using Kusto client's  `execute_query` method.

The queries I get are extremely similar to this:
```kql
StormEvents
| where ingestion_time() > ago(1h)
| summarize
    count_matching_regex_State=countif(State matches regex "[A-Z]*"),
    count_not_empty_State=countif(isnotempty(State))
| summarize
    Matching_State=sum(count_matching_regex_State),
    NotEmpty_State=sum(count_not_empty_State)
| project
    ratio_State=todouble(Matching_State) / todouble(Matching_State + NotEmpty_State)
| project
    ratio_State=iff(isnan(ratio_State), 0.0, round(ratio_State, 3))
```

I've been getting hit by the following error: `azure.kusto.data.exceptions.KustoApiError: Request is invalid and cannot be processed: Syntax error: SYN0001: I could not parse that, sorry. [line:position=0:0]`. However, when debugging, I've taken the query as it is, and ran it on my clusters thru the Kusto Web UI on Azure.

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

No, when ran the query returns the expected result on Kusto Web UI.

#### Output of ``pip freeze`` 
appnope==0.1.3
astroid==2.12.13
asttokens==2.0.8
attrs==22.2.0
autopep8==1.7.0
azure-common==1.1.28
azure-core==1.26.0
azure-functions==1.12.0
azure-identity==1.11.0
azure-kusto-data==3.1.3
azure-mgmt-core==1.3.2
azure-mgmt-securityinsight==1.0.0
backcall==0.2.0
bcrypt==4.0.0
blis==0.9.1
cachetools==5.2.0
catalogue==2.0.8
certifi==2022.6.15.1
cffi==1.15.1
cfgv==3.3.1
charset-normalizer==2.1.1
click==8.1.3
confection==0.0.1
coverage==7.0.1
cryptography==38.0.1
cycler==0.11.0
cymem==2.0.6
debugpy==1.6.3
decorator==5.1.1
dill==0.3.6
distlib==0.3.6
docopt==0.6.2
docutils==0.19
entrypoints==0.4
exceptiongroup==1.1.0
executing==1.0.0
fastai==2.7.9
fastcore==1.5.26
fastdownload==0.0.7
fastprogress==1.0.3
filelock==3.9.0
fonttools==4.37.1
google-auth==2.11.0
identify==2.5.11
idna==3.3
ijson==3.1.4
iniconfig==2.0.0
ipykernel==6.15.3
ipython==8.5.0
isodate==0.6.1
isort==5.11.4
jedi==0.18.1
Jinja2==3.1.2
joblib==1.1.0
jupyter-core==4.11.1
jupyter_client==7.3.5
kiwisolver==1.4.4
kubernetes==24.2.0
langcodes==3.3.0
lazy-object-proxy==1.8.0
MarkupSafe==2.1.1
matplotlib==3.5.3
matplotlib-inline==0.1.6
mccabe==0.7.0
msal==1.20.0
msal-extensions==1.0.0
msrest==0.7.1
murmurhash==1.0.8
nest-asyncio==1.5.5
nodeenv==1.7.0
numpy==1.23.4
oauthlib==3.2.0
openshift==0.13.1
openshift-client==1.0.17
packaging==21.3
pandas==1.4.4
paramiko==2.11.0
parso==0.8.3
pathy==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
pipreqs==0.4.11
platformdirs==2.6.2
pluggy==1.0.0
portalocker==2.5.1
pre-commit==2.21.0
preshed==3.0.7
prompt-toolkit==3.0.31
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.9.1
pycparser==2.21
pydantic==1.9.2
Pygments==2.13.0
PyJWT==2.5.0
pylint==2.15.9
PyNaCl==1.5.0
pyparsing==3.0.9
pytest==7.2.0
pytest-cov==4.0.0
python-dateutil==2.8.2
python-dotenv==0.21.0
python-string-utils==1.0.0
pytz==2022.2.1
PyYAML==6.0
pyzmq==23.2.1
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.1.2
scipy==1.9.1
sentencepiece==0.1.97
six==1.16.0
smart-open==5.2.1
spacy==3.4.1
spacy-legacy==3.0.10
spacy-loggers==1.0.3
srsly==2.4.4
stack-data==0.5.0
thinc==8.1.1
threadpoolctl==3.1.0
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.6
torch==1.12.1
torchvision==0.13.1
tornado==6.2
tqdm==4.64.1
traitlets==5.4.0
typer==0.4.2
types-cryptography==3.3.23
typing_extensions==4.3.0
urllib3==1.26.12
virtualenv==20.17.1
wasabi==0.10.1
wcwidth==0.2.5
websocket-client==1.4.1
wrapt==1.14.1
yarg==0.1.9

**Comment by yogilad** [comment]
Can you share the resulting text which fails the query?
Please also share a client activity (request) id of the failure.

**Comment by FaresKi** [comment]
I wasn't escaping my special characters correctly:
```py
def match_regex_statements(field, regex_patterns):
            return " or ".join(
                list(
                    map(
                        lambda pattern: f'{field} matches regex @"{pattern}"',
                        regex_patterns,
                    )
                )
            )
```

**Comment by AsafMah** [comment]
Great, closing.
