### ISSUE TITLE
The constraints on `azure-core` in `azure-kusto-data` v4.1.0 is missing a comma

### ISSUE THREAD

**Issue by xylar** [Azure/azure-kusto-python#453]
When building the latest release (v4.1.0) of  `azure-kusto-data` on conda-forge:
https://github.com/conda-forge/azure-kusto-data-feedstock/pull/20
I'm running into issues with the constraint on `azure-core` here:
https://github.com/Azure/azure-kusto-python/blob/v4.1.0/azure-kusto-data/setup.py#L48
It should be:
```
azure-core>=1.11.0,<2
```
with a comma.

Thanks!

**Comment by AsafMah** [comment]
Fixed in v4.1.1, thanks for your patience.
