### ISSUE TITLE
Queries with control commands and leading comments raise an error using API

### ISSUE THREAD

**Issue by catando** [Azure/azure-kusto-python#456]
When running a control command with comments preceding the query, an error is returned.

## Expected behavior

The query executes without raising an exception.

## Steps to reproduce

Execute a query like this one using the python library (note that it works fine using the ADX Web UI):

```
// This is a leading comment explaining something
.create-or-alter function demo_function() {
    datatable(a_date:string) [
        "2023-01-01T00:00:00Z"
    ]
}
```

## Comments

https://github.com/Azure/azure-kusto-python/blob/921249ccd8ea793e086369ed2b30a833805555e2/azure-kusto-data/azure/kusto/data/aio/client.py#L49-L51 and also https://github.com/Azure/azure-kusto-python/blob/921249ccd8ea793e086369ed2b30a833805555e2/azure-kusto-data/azure/kusto/data/client.py#L158-L160 are where a distinction is made between management commands and queries, but it's done on the basis of the very first character, which is always a `/` if there are leading comments.

## Possible solution

Trim leading comments before evaluating the first character.

**Comment by AsafMah** [comment]
We try to avoid parsing KQL fully in the client side.
This is a convenience method, you can use the explicit `execute_mgmt()` if you want a management command.
