### ISSUE TITLE
IncompleteRead error when using client.execute_streaming_query()

### ISSUE THREAD

**Issue by AdrianGScorp** [Azure/azure-kusto-python#457]
I tryed to run the following Code where I append id's from a table into a list for every row in the table. Somhow this alsways crashes after some time with an IncompleteRead Error. Anyone knows the reason and a solution for this?

`kcsb = KustoConnectionStringBuilder.with_az_cli_authentication(cluster)
client = KustoClient(kcsb)
kcsb.Streaming = True

response = client.execute_streaming_query(db, query)
table = response.iter_primary_results()

item_list = []
for i, row in enumerate(next(table)):
    item_list.append(row['Id'])`

Error Message:
ProtocolError: ('Connection broken: IncompleteRead(4717565 bytes read)', IncompleteRead(4717565 bytes read))

**Comment by yogilad** [comment]
Can you send a client activity id for a repro of the problem?
Also, if the time it takes for your to read the response is long, you may want to set the timeout client request property to a higher value. The default timeout is 4m.

https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/request-properties#clientrequestproperties-options

**Comment by yogilad** [comment]
@AdrianGScorp, did this help? Can we close the issue?
