### ISSUE TITLE
KQL Parser in Python

### ISSUE THREAD

**Issue by meghdivya** [Azure/azure-kusto-python#467]
**Is your feature request related to a problem? Please describe.**
Currently there is no parser available to validate kusto query syntax in python.

**Describe the solution you'd like**
I would like to have a parser like sqlglot for sql, ast for python that can parse kql syntax.

**Additional context**
We need this for NL to KQL translation experiments.

**Comment by AsafMah** [comment]
We do not have this in python and don't intend to make one at this moment.

https://www.nuget.org/packages/Microsoft.Azure.Kusto.Language/
https://www.npmjs.com/package/@kusto/monaco-kusto?activeTab=dependencies
