### ISSUE TITLE
Validating commands or queries before execute()

### ISSUE THREAD

**Issue by sadatnfs** [Azure/azure-kusto-python#488]
**Background**
We have CI/CD pipelines set up to upload ADX functions to our cluster, and we're using the Python SDK. However, the only way to know whether the ADX function I'm inputting is valid, is by just trying to execute it, and returning an error.

I'm looking for a way to simplify validate whether a piece of input (where it's a query or a `.create` call) is error-free and does not cause issues, BEFORE I run the execute().

Use case: I will add the validation as a test whenever someone opens a PR; the function will parse the input query strings and validate whether they are syntactically correct, and such.

**Feature Request**
I would like to have some method available to lint/parse/validate a piece of ADX query or command.
I'm guessing this can be baked into execute() as some "dry run" option, so that that option will not actually push the function itself, but check for whether it can.

**Alternatives considered**
I haven't found anything worthwhile or helpful to go down this route unfortunately.

**Comment by yogilad** [comment]
Kusto Language is available in Java Script and C# only. 
If you must deploy the validation as a service or interop in one of these languages.
