### ISSUE TITLE
ResourceWarning - Session not closed somewhere

### ISSUE THREAD

**Issue by cbb330** [Azure/azure-kusto-python#492]
#### Code Sample, a copy-pastable example if possible

```python
def get_kusto_client(
    connection_string: str, client_id: str, client_secret: str, authority_id: str
) -> KustoClient:
    kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(
        connection_string, client_id, client_secret, authority_id
    )
    return KustoClient(kcsb)


kusto_client = get_kusto_client(
    connection_string, client_id, client_secret, authority_id
)
with kusto_client:
    (do stuff)
    ...
    (stop doing stuff)
<- here is where warning throws
```
#### Problem description
Hello friends,

Even after closing the kusto client object, there is a session left open somewhere behind the public API. Using `with` context manager or even calling `.close()` explicitly does not close this session.

```
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=18, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('2620:119:5053:1b::3aa1', 53967, 0, 0), raddr=(
'2603:1037:1:148::e', 443, 0, 0)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

(not sure if it helps that above ipv6 addr's are microsoft owned and likely owned by azure data explorer)

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 
only python client related

#### Output of ``pip freeze`` 
unfortunately LinkedIn's package management is inhouse and the output would be not helpful. i'm using 
```
    "azure-kusto-data": "pypi:azure-kusto-data:4.2.0",
    "pyOpenSSL": "pypi:pyOpenSSL:23.2.0",
```

if that helps!

**Comment by AsafMah** [comment]
Can you be more specific?
What actions do you do with the client?

**Comment by cbb330** [comment]
sorry, I had this warning filtered and hidden for a while, now when I remove the filter, it doesn't procure anymore.

we can chalk this up to user error since it cannot repro
