### ISSUE TITLE
KustoAuthenticationError- ParseError('syntax error: line 1, column 0')

### ISSUE THREAD

**Issue by sylwiakrakowska** [Azure/azure-kusto-python#497]
Team,

Getting: ParseError('syntax error: line 1, column 0') within KustoAuthenticationError in Azure Kusto Data lib:

KustoAuthenticationError: KustoAuthenticationError('UserPassTokenProvider', 'ParseError('syntax error: line 1, column 0')', '{'authority': 'https://login.microsoftonline.com/<###>', 'client_id': <###>', 'username': '<#>', 'kusto_uri': '<##>'}')

<###>  -  put for security reason.
method for authentication - KustoConnectionStringBuilder.with_aad_user_password_authentication(cluster, username, password, authority_id)

**Comment by AsafMah** [comment]
I couldn't recreate this error.
Can you give more details? 
Specifically, what version of python do you use, what version of the library do you use?

In what format is your authority id? 

It's hard to see

**Comment by AsafMah** [comment]
I'm closing for now, please free to open again when you can provide the details asked.
