### ISSUE TITLE
Test suite fails with environment variables unset

### ISSUE THREAD

**Issue by aaronwolmutt** [Azure/azure-kusto-python#500]
#### Problem description

I'm trying to build and test the SDK. From the CONTRIBUTING.md perquisites it says: 

## Prerequisites
In order to run E2E tests, you need a Kusto database you have admin rights on.
A Kusto free cluster is the easiest way to acquire one.
You can cerate a free Kusto cluster here: https://dataexplorer.azure.com/home

You should set then following environment vars where you run E2Es (in IDE run config, shell window, computer, etc).
```shell
ENGINE_CONNECTION_STRING=<Your cluster URI>
DM_CONNECTION_STRING=<Your ingest cluster URI>
TEST_DATABASE=<The name of the database>
```
When I set the environment and run the tests I'm getting several failures due to the environment not being set. Ie, 

<img width="1125" alt="image" src="https://github.com/Azure/azure-kusto-python/assets/46609878/dff8aeec-bd04-4f7b-888d-73986900b662">

**Comment by AsafMah** [comment]
This documentation is old and misleading, we will work on fixing it.

**Comment by yogilad** [comment]
Latest commit should make it simple to use.
There are instructions in the contribution guide doc
