### ISSUE TITLE
KustoAsyncUsageError is thrown every time when using managed identity authentication method

### ISSUE THREAD

**Issue by kshilovskiy** [Azure/azure-kusto-python#532]
#### Code Sample, a copy-pastable example if possible

```python
with KustoClient(query_connection_string_builder) as kusto_client:
        with QueuedIngestClient(ingest_connection_string_builder) as queued_ingest_client:
               .....

```
#### Problem description
The above code results in
```
KustoAsyncUsageError: Method Can't close async token provider with sync close can't be called from a synchronous client
```
when using `KustoConnectionStringBuilder.with_aad_managed_service_identity_authentication()` method for creating the connection string.

The bug was introduced in version 4.3.1 with the following code in `azure-kusto-data/azure/kusto/data/_token_providers.py`:
<img width="637" alt="image" src="https://github.com/Azure/azure-kusto-python/assets/1021893/f8161427-c220-4917-a810-71ad37228562">

Commit: https://github.com/Azure/azure-kusto-python/commit/cd0ee8a3856e585e98199dbd94a477bbc2438197

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

<details>

[paste the output of ``pip freeze`` here below this line]
azure-kusto-data==4.4.0
azure-kusto-ingest==4.4.0

</details>

**Comment by AsafMah** [comment]
Should be fixed in 4.4.1
