### ISSUE TITLE
Fetching a large dataset more tha  64MB, returns None to execute function.

### ISSUE THREAD

**Issue by naman-shah-2829** [Azure/azure-kusto-python#536]
When I am using the execute() function to fetch data from the Kusto using python, if the response is more than 64MB, it returns me None rather than returning partial data how it does in ADX. I dont want to use the notruncation method as it can lead the dead kernel situations. Is there any other way where I can receive the partial data ?

**Comment by AsafMah** [comment]
64MB is the default limit, you can use notruncation in your query like so to avoid this:
```kql
set notruncation;
MyTable | take 1000000
```

See https://learn.microsoft.com/en-us/azure/data-explorer/kusto/concepts/query-limits for more details

**Comment by AsafMah** [comment]
You can use streaming query to get the results as they arrive-
```python
            result = client.execute_streaming_query(self.test_db, self.streaming_test_table_query + ";" + self.streaming_test_table_query)
            for primary in result.iter_primary_results():
                for row in primary:
                    # work on rows
```

**Comment by AsafMah** [comment]
Closing, feel free to open with a comment.
