### ISSUE TITLE
Missing client activity id

### ISSUE THREAD

**Issue by rishimalhotra2** [Azure/azure-kusto-python#537]
Is there a way to get the client activity id for each query execution?

To be more specific,

response = client.execute(db, query), how do i get the ClientActivityId for that query execution?

**Comment by AsafMah** [comment]
If you want to identify your request, the recommended way is to set the client request id by yourself like so:

```python
props = ClientRequestProperties()
props.client_request_id = "my_id"
result = client.execute("Data", "AllDataTypes", props) 
```

**Comment by AsafMah** [comment]
Closing, feel free to open with a comment.
