### ISSUE TITLE
Authenticate with Federated identity credentials to a AAD application for KustoConnectionStringBuilder 

### ISSUE THREAD

**Issue by navapro** [Azure/azure-kusto-python#549]
**Is your feature request related to a problem? Please describe.**
I don't think there is any current method in the class KustoConnectionStringBuilder for using FIC to authenticate an AAD application and accessing Kusto that way.

**Describe the solution you'd like**
Currently I'm Using ManagedIdentityCredential to get the MSI credentials first then ClientAssertionCredential to authenticate into the application, finally getting the token from that credential and using KustoConnectionStringBuilder.with_aad_application_token_authentication to access Kusto. I would like to use a similar logic to build a new method `KustoConnectionStringBuilder.with_aad_application_federated_identity_authentication`.

**Describe alternatives you've considered**
I've considered using with_aad_managed_service_identity_authentication, this doesn't support cross tenant Identities, alternatively this function could be updated to ingest a tenant ID to achieve the same results.

**Additional context**
While working on an internal Microsoft project I've notice this feature doesn't exist and would like to implement the following as I believe this will be more useful in the future.

**Comment by AsafMah** [comment]
We have a method - `with_azure_token_credential` - that accepts a TokenCredential object for auth. 

You can pass your ClientAssertionCredential directly to that, saving you the step.

Do you think we still need the new method when this is available?

What would the signature for your method look like?

**Comment by AsafMah** [comment]
Closing this issue due to a lack of response, if you still want to contribute this feature please let us know.
