### ISSUE TITLE
KustoApiError: Request is invalid and cannot be processed: Service request failed. Status: 403 (Forbidden)

### ISSUE THREAD

**Issue by hoofir** [Azure/azure-kusto-python#556]
Hi,

I am using the following method to read a table from a database in Azure Data Explorer using kusto for python library:

This method to connect using service principal:

```
from azure.kusto.data import KustoClient
from azure.kusto.data import KustoConnectionStringBuilder

connection = KustoConnectionStringBuilder.with_aad_application_key_authentication(client_id, client_secret, tenant_id)

with KustoClient(connection) as client:
    response = client.execute_query(database_name, query)
    print(response.primary_results[0])
```

regarding the `database_name`, `query` and access for service principal, everything seems OK. Service principal has at database level as well as cluster level all the Admin, and Viewer rights.

PS: When I use my own identity to fetch the data it works but with service principal it returns the below error!!
Also, I have to mention that the connection with cluster works well and I get the connection and the error happens at this line --->  
**`response = client.execute_query(database_name, query)`**

```
.
.
.
HTTPError: 400 Client Error: BadRequest for url: [https://](https://****.***.kusto.windows.net/v2/rest/query)

The above exception was the direct cause of the following exception:
KustoApiError        Traceback (most recent call last)
.
.
.
KustoApiError: Request is invalid and cannot be processed: Service request failed.
Status: 403 (Forbidden)
.
.
.
Headers:
Strict-Transport-Security: REDACTED
traceresponse: REDACTED
mise-correlation-id: REDACTED
Content-Length: 0
Date: Thu, 31 Oct 2024 09:12:35 GMT

```

**Comment by AsafMah** [comment]
Can we get a client request id to see it from our side?

**Comment by hoofir** [comment]
Excuse my noob question, what is client request id ? :)

**Comment by elirandav** [comment]
@hoofir 
The response object should contain a property named `clientRequestId`

**Comment by hoofir** [comment]
I cannot find it in the response...

but when I use msal package to call API, I can see that, which is:

```
Error details:
ClientRequestId='unspecified;
```
