### ISSUE TITLE
0.0.11 failed authentication via AAD applicaiton id

### ISSUE THREAD

**Issue by kenzhan** [Azure/azure-kusto-python#62]
Application id look up under windows.net which fails the query execution 

Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS70001: Application with identifier '###' was not found in the directory windows.net

**Comment by kenzhan** [comment]
PR Change adal default endpoint (#58) is breaking backward compatibility. 

The workaround is to specify authority_id to the original default value "microsoft.com", but it should be exposed by connection string builder.

`KCSB.authority_id = "microsoft.com"`

**Comment by danield137** [comment]
Closing. Please reopen if not resolved.
