### ISSUE TITLE
Cannot import helpers

### ISSUE THREAD

**Issue by guruatmicrosoft** [Azure/azure-kusto-python#67]
Trying out samples listed @ https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-data/tests/sample.py
This line is failing,
from azure.kusto.data.helpers import dataframe_from_result_table

error: ImportError: No module named helpers
I am trying this on pyspark prompt, have installed python modules.

-
Thanks

**Comment by guruatmicrosoft** [comment]
This is what i notice in the directory structure -
ls -l /usr/local/lib/python2.7/dist-packages/azure/kusto/data/
total 84
-rw-rw-rw- 1 root root  1147 Sep 14 10:26 exceptions.py
-rw-rw-rw- 1 root root  2408 Sep 14 10:27 exceptions.pyc
-rw-rw-rw- 1 root root    45 Sep 14 10:26 __init__.py
-rw-rw-rw- 1 root root   228 Sep 14 10:27 __init__.pyc
-rw-rw-rw- 1 root root 14056 Sep 14 10:26 request.py
-rw-rw-rw- 1 root root 15312 Sep 14 10:27 request.pyc
-rw-rw-rw- 1 root root 10205 Sep 14 10:26 _response.py
-rw-rw-rw- 1 root root 13320 Sep 14 10:27 _response.pyc
-rw-rw-rw- 1 root root  4484 Sep 14 10:26 security.py
-rw-rw-rw- 1 root root  4104 Sep 14 10:27 security.pyc
-rw-rw-rw- 1 root root    39 Sep 14 10:26 _version.py
-rw-rw-rw- 1 root root   223 Sep 14 10:27 _version.pyc

**Comment by guruatmicrosoft** [comment]
For now i have copied helpers.py in the dist-packages folder and i can import, but i am running into an error while creating dataframe - '_KustoResultTable' object has no attribute 'rows'

I have verified my query response has KustoTable and also printed individual rows and could confirm data in row matches with the query run. 

Looking for your inputs to unblock.

-
Thanks

**Comment by danield137** [comment]
Hi @guruatmicrosoft , `master` branch is ahead of latest release, and so examples are of the future version.

I will release the next version shortly (0.0.12). would you kindly update if that solves the issue? Apologizes for the mix-up.

**Comment by gramarao** [comment]
Sure, I will give it a try and if its fine I can close the issue once I test with 0.0.12.

**Comment by danield137** [comment]
Closing. Please reopen if not resolved.
