### ISSUE TITLE
AAD authentication failed since v0.0.16 onwards

### ISSUE THREAD

**Issue by hexadite-lior** [Azure/azure-kusto-python#83]
The error raised before asking for authentication using device code.
bug doesn't exist in version 0.0.15

KustoServiceError: (KustoServiceError(...), [{'Message': 'Authorization has been denied for this request.'}])
 
![image](https://user-images.githubusercontent.com/19686267/49827207-7207d000-fd91-11e8-8f43-aa71a619de3c.png)

**Comment by toshetah** [comment]
This breaking change is documented in the release note of version 0.0.16 .
Please take a look at https://github.com/Azure/azure-kusto-python/releases/tag/v0.0.16
If you define KustoConnectionStringBuilder.with_aad_device_authentication , does it work?

**Comment by hexadite-lior** [comment]
Thanks! i might have missed that... for some reason i thought anonymous==device login...

**Comment by ZeljkoArsic** [comment]
I have been using KustoConnectionStringBuilder.with_aad_device_authentication, and after I have entered the code I got exact same error. 

![image](https://user-images.githubusercontent.com/50910326/60871219-9a29b580-a232-11e9-8efd-a91e371d540f.png)

I am using version 0.0.30.
