### ISSUE TITLE
cannot import name 'KustoClient'

### ISSUE THREAD

**Issue by nataliabernardo** [Azure/azure-kusto-python#86]
Hi, I'm trying to import Kusto Client using Azure notebooks but I'm facing some issues.
First, I typed "!pip install azure-kusto-data" and it resulted:
Requirement already satisfied: azure-kusto-data in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (0.0.11)
Requirement already satisfied: adal>=1.0.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from azure-kusto-data) (1.2.0)
Requirement already satisfied: six>=1.10.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from azure-kusto-data) (1.11.0)
Requirement already satisfied: requests>=2.13.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from azure-kusto-data) (2.20.1)
Requirement already satisfied: pandas>=0.15.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from azure-kusto-data) (0.22.0)
Requirement already satisfied: azure-nspkg>=2.0.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from azure-kusto-data) (3.0.2)
Requirement already satisfied: python-dateutil>=2.6.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from azure-kusto-data) (2.7.5)
Requirement already satisfied: cryptography>=1.1.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from adal>=1.0.0->azure-kusto-data) (2.3.1)
Requirement already satisfied: PyJWT>=1.0.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from adal>=1.0.0->azure-kusto-data) (1.7.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from requests>=2.13.0->azure-kusto-data) (2018.10.15)
Requirement already satisfied: idna<2.8,>=2.5 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from requests>=2.13.0->azure-kusto-data) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from requests>=2.13.0->azure-kusto-data) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from requests>=2.13.0->azure-kusto-data) (3.0.4)
Requirement already satisfied: pytz>=2011k in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from pandas>=0.15.0->azure-kusto-data) (2018.7)
Requirement already satisfied: numpy>=1.9.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from pandas>=0.15.0->azure-kusto-data) (1.14.6)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from cryptography>=1.1.0->adal>=1.0.0->azure-kusto-data) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from cryptography>=1.1.0->adal>=1.0.0->azure-kusto-data) (1.11.5)
Requirement already satisfied: pycparser in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=1.1.0->adal>=1.0.0->azure-kusto-data) (2.19)
In [7]:

Later, I typed "from azure.kusto.data import KustoClient", but got the result:
"ImportError: cannot import name 'KustoClient'"

Have you seen this error before or have a clue about the reason?
Thank you,
Natalia

**Comment by toshetah** [comment]
Hi nataliabernardo,

There are two different issues here.
First, you are trying to install a package that is already installed.
If you want to override the existing package (version 0.0.11) in Azure notebooks, you can run the following:
!pip install azure-kusto-data==0.0.19

The Second issue is that you are not importing correctly KustoClient.
You should import it as it appears in the [example](https://github.com/Azure/azure-kusto-python/blob/27ae1653b562b9a5d67dc4c2598d8b836f915499/azure-kusto-data/tests/sample.py#L3).
Where did you find the line you were using to import KustoClient? Is it documented like that somewhere?

Thanks,
Tomer

**Comment by toshetah** [comment]
Hi nataliabernardo,

Can you please update on your status? Can we close this issue?

Thanks,
Tomer

**Comment by nataliabernardo** [comment]
Hi toshetah,

Thanks a lot, it worked! You can close this issue.
Answering your question, I followed the steps documented [here](https://docs.microsoft.com/en-us/azure/kusto/tools/azurenotebooks).

Thank you,
Natalia

**Comment by toshetah** [comment]
Great. We'll update the wrong documentation. Thanks for reporting!
