### ISSUE TITLE
AdalError "AADSTS50079" for MFA

### ISSUE THREAD

**Issue by sbkirkwood** [Azure/azure-kusto-python#89]
When trying to authenticate with Kusto, I am getting the below error. Typically I manually go to a related site and force re-authentication with MFA, and that resolves the issue. However, that is not working also now. This error didn't exist for months, until the last month or two. Please suggest how to work around this. 

AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: The user is required to use multi-factor authentication.\r\nTrace ID: 8d4704cf-5c83-42bb-860b-7a2180d1fa00\r\nCorrelation ID: 87014a28-6bc1-4413-8592-ec1aac63646e\r\nTimestamp: 2018-12-31 20:57:33Z","error_codes":[50079],"timestamp":"2018-12-31 20:57:33Z","trace_id":"8d4704cf-5c83-42bb-860b-7a2180d1fa00","correlation_id":"87014a28-6bc1-4413-8592-ec1aac63646e","suberror":"basic_action"}

**Comment by vladikbr** [comment]
To the best of my understanding, you are an MSFT employee authenticating from outside MS corpnet.
In this scenario, MSFT AAD tenant is configured to demand MFA. If you are using a .NET client that can present UI and acquire the second factor, this is typically not an issue. However, you are using Python where there is no support for interactive authentication, hence your problem.
The MFA requirement from outside corpnet is not a new feature, it has been around for well over a year, so I find it hard to believe your statement that this exact scenario worked for you until two months ago.
There could have been other factors you were not explicitly aware of, e.g., VPN (although I am not sure id the MFA requirement can be relaxed over VPN).
