### ISSUE TITLE
Tenant ID for AAD-Federated

### ISSUE THREAD

**Issue by yzhong94** [Azure/azure-kusto-python#90]
I normally use AAD-Federated to login on Kusto.Explorer.  What's my tenant ID in this case?  Trying to use this code:
```
# In case you want to authenticate with AAD username and password
username = "<username>"
password = "<password>"
kcsb = KustoConnectionStringBuilder.with_aad_user_password_authentication(cluster, username, password, authority_id)
```

**Comment by vladikbr** [comment]
The easiest way is to navigate to [https://ms.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Properties](https://ms.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Properties) and use the GUID labeled Directory ID. That is your AAD Tenant ID (also known as Authority ID or Directory ID).
