### ISSUE TITLE
How to use for internal federated Kusto Cluster

### ISSUE THREAD

**Issue by prbajrac** [Azure/azure-kusto-python#94]
Hi, I am using internal AAD Federated cluster to access the cluste in Kusto explorer via being a part of security group. How would I go about adding that type of connection in the script ? Using my Azure Credentials does not seem to work.

Data Source=https://ar****d.kusto.windows.net:443;
Initial Catalog=NetDefaultDB;
AAD Federated Security=True

**Comment by toshetah** [comment]
Hi, I am not sure I fully understand what you are asking for.
Which one of the [supported authentication methods](https://github.com/Azure/azure-kusto-python#authentication-methods) are you trying to use?
Once you've chosen one, please see our [samples page](https://github.com/Azure/azure-kusto-python/blob/c5c01b2194f2fa326bd13bfe8970b6663dc4ad12/azure-kusto-data/tests/sample.py#L8) how to use each one them.

In case you need further help, please reply what is the authentication method you are trying to use, and a code snippet.

**Comment by toshetah** [comment]
Hi prbajrac,

Can you please update on your status? Can we close this issue?

Thanks,
Tomer

**Comment by prbajrac** [comment]
Hi, this issue can be closed for now. I will repoen another if required. Thanks you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
