### ISSUE TITLE
Why is there random.choice used in KustoIngestClient?

### ISSUE THREAD

**Issue by truekonrads** [Azure/azure-kusto-python#95]
Hello,

Why is random.choice used in `KustoIngestClient` to select details from container and queues:

*  https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-ingest/azure/kusto/ingest/_ingest_client.py#L56
* https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-ingest/azure/kusto/ingest/_ingest_client.py#L93
* https://github.com/Azure/azure-kusto-python/blob/master/azure-kusto-ingest/azure/kusto/ingest/_ingest_client.py#L112

Is there really no better strategy than to pick at random?

**Comment by toshetah** [comment]
Hi Konrads,

Can we close this issue? 

Thanks,
Tomer

**Comment by truekonrads** [comment]
Hi,

Apologies for late reply. I was reading library code to understand how ingestion works and spotted these. Reason for me raising this question/issue is that for library code, such decision may lead to unexpected results - perhaps some queues or containers are for different purposes. I would suggest that the decision logic is exposed to the user as an  initialization argument.

**Comment by toshetah** [comment]
You can see in [_resource_manager](https://github.com/Azure/azure-kusto-python/blob/c5c01b2194f2fa326bd13bfe8970b6663dc4ad12/azure-kusto-ingest/azure/kusto/ingest/_resource_manager.py#L107) that the different logic queues/containers are divided into the correct members.
I don't see any reason a customer would like to change the random choice of the container. If you were able to change this logic, what would you choose? And why?
What scenario is conflicting for you?
